### ISSUE TITLE
No role-specific documentation

### ISSUE THREAD

**Issue by JAORMX** [freeipa/ansible-freeipa#10]
There are no docs for the individual roles in the roles/ directory. this would be useful.

**Comment by t-woerner** [comment]
There are docs for the server and client roles in the SERVER and CLIENT md file.

More to come.

**Comment by kamilzabielski** [comment]
@JAORMX What is missing from your perspective?
@t-woerner How about putting them as section in `README.md` or move these two files to `root` directory of specific role?

**Comment by dawud** [comment]
I just submitted https://github.com/freeipa/ansible-freeipa/pull/54 to address this

**Comment by t-woerner** [comment]
Closing as this has been fixed.
