### ISSUE TITLE
ImportError: No module named 'ipalib.install'

### ISSUE THREAD

**Issue by 3coma3** [freeipa/ansible-freeipa#100]
Target: Ubuntu 16.04.6 LTS
Ansible host: Linux Mint 19.1
Ansible: 2.8.2
ansible-freeipa: latest from git
ipalib: 4.6.5

The ipaserver role fails to apply with this error. A quick grep shows the import at various files:
```
grep -R "ipalib.install" external/
external/ansible-freeipa/plugins/module_utils/ansible_freeipa_module.py:    from ipalib.install.kinit import kinit_password
external/ansible-freeipa/roles/ipaclient/library/ipaclient_get_facts.py:        from ipalib.install import sysrestore
external/ansible-freeipa/roles/ipaclient/module_utils/ansible_ipa_client.py:        from ipalib.install import sysrestore
external/ansible-freeipa/roles/ipaclient/module_utils/ansible_ipa_client.py:        from ipalib.install import certmonger
external/ansible-freeipa/roles/ipaclient/module_utils/ansible_ipa_client.py:        from ipalib.install import certstore
external/ansible-freeipa/roles/ipaclient/module_utils/ansible_ipa_client.py:        from ipalib.install.kinit import kinit_keytab, kinit_password
external/ansible-freeipa/roles/ipareplica/module_utils/ansible_ipa_replica.py:    from ipalib.install import certstore, sysrestore
external/ansible-freeipa/roles/ipareplica/module_utils/ansible_ipa_replica.py:    from ipalib.install.kinit import kinit_keytab
external/ansible-freeipa/roles/ipaserver/library/ipaserver.py:    from ipalib.install.sysrestore import SYSRESTORE_STATEFILE
external/ansible-freeipa/roles/ipaserver/module_utils/ansible_ipa_server.py:    from ipalib.install import certmonger, sysrestore
```
And I see try blocks for this error for example in roles/ipaserver/library/ipaserver.py:
```
199 import os
200 from six.moves.configparser import RawConfigParser
201 from ansible.module_utils.basic import AnsibleModule
202 try:
203     from ipalib.install.sysrestore import SYSRESTORE_STATEFILE
```
However there is not such try block in roles/ipaserver/module_utils/ansible_ipa_server.py

```
fatal: [tftest-ipaserver]: FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to 10.40.0.156 closed.\r\n",
    "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/home/zohl2ooPh4wah4tu-ansible/.ansible/tmp/ansible-tmp-1563752899.261556-204695747682928/AnsiballZ_ipaserver_test.py\", line 114, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/zohl2ooPh4wah4tu-ansible/.ansible/tmp/ansible-tmp-1563752899.261556-204695747682928/AnsiballZ_ipaserver_test.py\", line 106, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/zohl2ooPh4wah4tu-ansible/.ansible/tmp/ansible-tmp-1563752899.261556-204695747682928/AnsiballZ_ipaserver_test.py\", line 49, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/usr/lib/python3.5/imp.py\", line 234, in load_module\r\n    return load_source(name, filename, file)\r\n  File \"/usr/lib/python3.5/imp.py\", line 170, in load_source\r\n    module = _exec(spec, sys.modules[name])\r\n  File \"<frozen importlib._bootstrap>\", line 626, in _exec\r\n  File \"<frozen importlib._bootstrap_external>\", line 665, in exec_module\r\n  File \"<frozen importlib._bootstrap>\", line 222, in _call_with_frames_removed\r\n  File \"/tmp/ansible_ipaserver_test_payload_ckmmq9aw/__main__.py\", line 53, in <module>\r\n  File \"/tmp/ansible_ipaserver_test_payload_ckmmq9aw/ansible_ipaserver_test_payload.zip/ansible/module_utils/ansible_ipa_server.py\", line 57, in <module>\r\nImportError: No module named 'ipalib.install'\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

Can others confirm?

**Comment by t-woerner** [comment]
Are you sure that your IPA version is 4.6.5? `SYSRESTORE_STATEFILE` is placed in `ipalib/install/sysrestore.py` since IPA release 4.5.0.

**Comment by 3coma3** [comment]
> Are you sure that your IPA version is 4.6.5? `SYSRESTORE_STATEFILE` is placed in `ipalib/install/sysrestore.py` since IPA release 4.5.0.

That's strange, the version reported by pip is in fact 4.6.5, freeipa/install is in fact in [https://github.com/freeipa/freeipa/tree/release-4-6-5/ipalib](https://github.com/freeipa/freeipa/tree/release-4-6-5/ipalib)

What I see is that installing ipalib (manually or via ansible pip module) renders a dist-package without the submodule. Might this be a problem with pip then?

**Comment by t-woerner** [comment]
Are you sure that pip was not skipping the installation maybe because there is already freeipa 4.3.1 installed (https://packages.ubuntu.com/de/xenial/net/freeipa-server)?

There is a version check in ansible_ipa_server to fail with IPA version < 4.5.0. How did this pass? What is the output of `python -c "from ipapython.version import NUM_VERSION; print(NUM_VERSION)"` on the node that should become the IPA server?

**Comment by t-woerner** [comment]
Please do not install distro and pip packages with different versions on the same machine. This is something that FreeIPA and also ansible-freeipa are not able to support.

**Comment by 3coma3** [comment]
Hi Tim, sorry for delay. I will verify this today and reopen if the version mismatch is not the cause. Thanks for your support

**Comment by 3coma3** [comment]
> Are you sure that pip was not skipping the installation maybe because there is already freeipa 4.3.1 installed (https://packages.ubuntu.com/de/xenial/net/freeipa-server)?
> 
> There is a version check in ansible_ipa_server to fail with IPA version < 4.5.0. How did this pass? What is the output of `python -c "from ipapython.version import NUM_VERSION; print(NUM_VERSION)"` on the node that should become the IPA server?

@t-woerner : 

```
terraform@tftest-ipaserver:~$ python -c "from ipapython.version import NUM_VERSION; print(NUM_VERSION)"
40605
terraform@tftest-ipaserver:~$ pip3 list
Package        Version               
-------------- ----------------------
asn1crypto     0.24.0                
cffi           1.12.3                
chardet        2.3.0                 
cryptography   2.7                   
decorator      4.0.6                 
dnspython      1.16.0                
gssapi         1.6.0                 
ipalib         4.6.5                 
ipaplatform    4.6.5                 
ipapython      4.6.5                 
netaddr        0.7.19                
netifaces      0.10.9                
pip            19.2.1                
pyasn1         0.4.5                 
pyasn1-modules 0.2.5                 
pycparser      2.19                  
pygobject      3.20.0                
python-apt     1.1.0b1+ubuntu0.16.4.5
python-ldap    3.2.0                 
requests       2.9.1                 
setuptools     20.7.0                
six            1.10.0                
slip           0.6.1                 
slip.dbus      0.6.1                 
ssh-import-id  5.5                   
urllib3        1.13.1                
wheel          0.29.0                
```

I can still reproduce this error. Fresh OS from ISO, ensured that no pip packages are installed by the OS.

Could we please reopen to further investigate this issue?

**Comment by t-woerner** [comment]
I will try to verify your issue with a fresh system installed without any pip3 packages. in your pip3 list there are
```
ipalib         4.6.5                 
ipaplatform    4.6.5                 
ipapython      4.6.5      
```
It is not supported to use these with the freeipa-server package 4.3.1 installed from ubuntu.

**Comment by t-woerner** [comment]
I just installed Ubuntu 16.04.5 server in a virtual machine. The server installation test is resulting in the exception `freeipa version '4.3.1' is too old`. 
Sadly there is a back trace and not a nice error message. I will add a try and except to catch this raise in ipaserver_test for ansible_ipa_server. I will also add the same for ipareplica_test and ipaclient_test.

**Comment by 3coma3** [comment]
> I just installed Ubuntu 16.04.5 server in a virtual machine. The server installation test is resulting in the exception `freeipa version '4.3.1' is too old`.
> Sadly there is a back trace and not a nice error message. I will add a try and except to catch this raise in ipaserver_test for ansible_ipa_server. I will also add the same for ipareplica_test and ipaclient_test.

Thanks a lot Thomas, there's the root cause then. Really appreciated.

In the meantime I will try to preinstall freeipa or add alternative repos (if they exist) from a playbook.

**Comment by 3coma3** [comment]
@t-woerner 

I can still reproduce with Ubuntu Bionic, as before, fresh installs from preseed / terraform.

pip reports:
```
ipaclient         4.8.0        
ipalib            4.8.0        
ipaplatform       4.8.0        
ipapython         4.8.0  
```

dpkg:
```
root@tftest-ipaserver:~# dpkg -l freeipa-*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                            Version                      Architecture                 Description
+++-===============================================-============================-============================-===================================================================================================
un  freeipa-admintools                              <none>                       <none>                       (no description available)
ii  freeipa-client                                  4.7.0~pre1+git20180411-2ubun amd64                        FreeIPA centralized identity framework -- client
ii  freeipa-common                                  4.7.0~pre1+git20180411-2ubun all                          FreeIPA centralized identity framework -- common files
ii  freeipa-server                                  4.7.0~pre1+git20180411-2ubun amd64                        FreeIPA centralized identity framework -- server
ii  freeipa-server-dns                              4.7.0~pre1+git20180411-2ubun all                          FreeIPA centralized identity framework -- IPA DNS integration
un  freeipa-server-trust-ad                         <none>                       <none>                       (no description available)
```
Any pointer will be really appreciated
