### ISSUE TITLE
ipagroup consecutive runs remove members when already exist

### ISSUE THREAD

**Issue by smo-west** [freeipa/ansible-freeipa#1004]
Issue description:
When rerunning the playbook that ensures the required groups are present with the required members, it removes existing member groups when giving the following error message:
**group_add_member: This entry is already a member**

`
- name: create group
  freeipa.ansible_freeipa.ipagroup:
    name: "{{ ipa_group }}"
    ipaadmin_password: "{{ ipa_password }}"
    ipaadmin_principal: "{{ ipa_user }}"
    group: "{{ member_group }}"
`

Expected behaviour: Group membership does not get removed when already present (either failure without changes, or OK without changes)

**Comment by t-woerner** [comment]
This is expected behaviour as you are operating on the group level and it is a set operation.
Please add `action: member` to work on the (group) member level instead. With the member action it is possible to ensure presence and absence of items in the group.
