### ISSUE TITLE
additional firewall ports need to be opened according to rh docs

### ISSUE THREAD

**Issue by RobVerduijn** [freeipa/ansible-freeipa#1021]
Hello,

According to [this image](https://access.redhat.com/webassets/avalon/d/Red_Hat_Enterprise_Linux-9-Installing_trust_between_IdM_and_AD-en-US/images/fc93488580ceb829bd9e8bf2379ea978/231_RHEL_troubleshooting_cross-forest_0422_firewall.png) from [this redhat doc ](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/installing_trust_between_idm_and_ad/index#ports-required-for-communication-between-idm-and-ad_installing-trust-between-idm-and-ad) chapter 6 (scroll a bit down to find the image)

The following ports should be opened between idm servers
CA 8443 TCP/TCP6 both directions
OCSP 8080 TCP/TCP6 both directions

I can't determine if that's only needed when there is an ad-trust configured on the idm domain.

Rob

**Comment by rjeffman** [comment]
These ports are used by dogtag/PKI. What is not clear to me yet, is if these ports need to be open when IPA is used.

**Comment by flo-renaud** [comment]
Hi,

On Fri, Jan 20, 2023 at 4:19 PM Rafael Guterres Jeffman <
***@***.***> wrote:

> These ports are used by dogtag/PKI. What is not clear to me yet, is if
> these ports need to be open when IPA is used.
>
443 and 80 must be open but 8443 and 8080 should be used only locally. More
info in
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/installing_identity_management/preparing-the-system-for-ipa-server-installation_installing-identity-management#port-requirements-for-idm_preparing-the-system-for-ipa-server-installation
:
*In addition, ports 8080, 8443, and 749 must be free as they are used
internally. Do not open these ports and instead leave them blocked by a
firewall. *

flo

**Comment by rjeffman** [comment]
Thank you, @flo-renaud !
