### ISSUE TITLE
RHEL8 NSS failures with ipaclient

### ISSUE THREAD

**Issue by sirwalrus** [freeipa/ansible-freeipa#104]
Somewhat related to https://github.com/freeipa/ansible-freeipa/issues/103.

During an initial playbook to configure ipaclient:

- include_role:
    name: ipaclient
  vars:
    ipaclient_realm: '{{ kerberos_realm }}'
    ipaclient_domain: "{{ kerberos_realm|lower }}"
    ipaadmin_principal: "{{ ipa_host_enrollment_principal }}"
    ipaadmin_password: "{{ ipa_host_enrollment_password }}"

.....................................................................

TASK [ipaclient : Install - Create IPA NSS database] **************************************************
fatal: [host.example.com]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'dnso'\n\nThe error appears to be in '/home/rdu/batkisso/git-work/CM/playbooks/playbooks/roles/ansible-freeipa/roles/ipaclient/tasks/install.yml': line 300, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Install - Create IPA NSS database\n      ^ here\n"}

**Comment by t-woerner** [comment]
This has been fixed already https://github.com/freeipa/ansible-freeipa/commit/743216b0db239fcebaa0403e20deea00e3cd5d57
It is part of the latest release 0.1.6: https://github.com/freeipa/ansible-freeipa/releases/tag/v0.1.6

**Comment by t-woerner** [comment]
Please give it a try

**Comment by sirwalrus** [comment]
worked liked a charm with 0.1.6. Thanks!
