### ISSUE TITLE
ipauser does not handle street address

### ISSUE THREAD

**Issue by parmstro** [freeipa/ansible-freeipa#1041]
A standard part of the user mailing address information is the street address. There is no variable to provide this in the ipauser module.

**Comment by rjeffman** [comment]
A few fields are missing in `ipauser`, in relation to FreeIPA CLI. The fields currently not available are:
* GECOS (fixed in #1039)
* street
* idp support attributes (to be added with external IDP support)
* smb attributes

Thank you for the report.
