### ISSUE TITLE
Can the roles be used idempotently?

### ISSUE THREAD

**Issue by CoaxVex** [freeipa/ansible-freeipa#105]
I have noticed that when I apply the ipaserver role to a system, the playbook fails on consecutive runs:
```
fatal: [ipa01.int.mydomain.org]: FAILED! => {"changed": false, "msg": "DNS zone int.mydomain.org. already exists in DNS and is handled by server(s): ipa01.int.mydomain.org."}
```
It doesn't happen with the ipareplica role, but it seems like it just skips most of its tasks. (I haven't tried the ipaclient role yet)

So: does it make sense to use these roles in an existing inventory and have them assigned / executed on every playbook run? Or are they meant to be used for setting up the infrastructure once?

**Comment by t-woerner** [comment]
Without _setup_dns the role can be used idempotently. I think I need to push the DNS checks further down after the other checks. This way the replica will be identified as already deployed and the DNS check will not fail as it will not be used.
But either way the DNS check code in IPA seems to need some work to make sure that the own instance will not be found as a conflicting DNS server.

**Comment by t-woerner** [comment]
This DNS issue has been fixed in IPA code with the commits

https://github.com/freeipa/freeipa/commit/dd7fdaa77d00042d44bec23291f0d0be36bead5e and 
https://github.com/freeipa/freeipa/commit/f80a6548ad8d0d21219ce26d3e819f7ad5f3663e
