### ISSUE TITLE
Playbook names cannot include hyphens in Ansible Galaxy Collections

### ISSUE THREAD

**Issue by eliba** [freeipa/ansible-freeipa#1064]
Hi all,

I installed this collection via `ansible-galaxy collection install freeipa.ansible_freeipa`, but I'm unable to use it:
1. My own custom playbook `ipaserver.yml`:
```
---
- ansible.builtin.import_playbook: freeipa.ansible_freeipa.install-server
```
2. Run `ansible-playbook -i ansible/devventory/ ansible/ipaserver.yml`
3. Output:
```
ERROR! Unable to retrieve file contents
Could not find or access '/var/local/repos/bliblablubb/ansible/install-server.yml' on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option
```
I read in [Ansible Galaxy documentation](https://docs.ansible.com/ansible/devel/collections_guide/collections_using_playbooks.html#using-a-playbook-from-a-collection) that playbook names cannot include `-` (hyphen/dash) characters, but only `_` (underscore).

When I rename playbooks in the `playbooks/` subfolder of this collection (e.g. `install-server.yml` -> `install_server.yml`), I can reference this in my playbook and it works correctly.

Is my observation correct, or did I miss something obvious when trying to use the collection this way? I could open a PR that renames playbooks, if that's helpful.

Thanks for this collection, it helps a lot!

**Comment by rjeffman** [comment]
The playbooks are meant as examples to ansible-freeipa usage and are not considered part of the collection itself. Only renaming them will not work, as they contain example data that need to be customized for use.

My suggestion is to copy the playbook to a "local playbook directory" and run the playbooks from there, or use them as a starting point for you own playbook.

**Comment by eliba** [comment]
I see, alright. I'll create my own playbook then and take the example one as a starting point. Thanks! :)
