### ISSUE TITLE
Reinitialize are failed to find the node in ipatopology segments

### ISSUE THREAD

**Issue by varunmylaraiah** [freeipa/ansible-freeipa#107]
Description of problem:
In ipatopology segments, reinitialize are failed to find the node are exists or not
 

Version-Release number of selected component (if applicable):
ansible-freeipa-0.1.6-2.el8.noarch

Steps to Reproduce:

cat delete-topologysegment.yml

- name: Playbook to handle topologysegment
  hosts: ipaserver
  become: true

  tasks:
  - name: Delete topology segment
    ipatopologysegment:
      ipaadmin_password: <xxxxxxxxx>
      suffix: ca
      left: qwerty
      right: asdfg
      state: absent

$ansible-playbook -vv -i inventory/hosts.topologysegment delete-topologysegment.yml 
ansible-playbook 2.8.2
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.8 (default, Jul  3 2019, 10:59:07) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
No config file found; using defaults

PLAYBOOK: delete-topologysegment.yml ********************************************************************************
1 plays in delete-topologysegment.yml

PLAY [Playbook to handle topologysegment] ***************************************************************************

TASK [Gathering Facts] **********************************************************************************************
task path: /root/delete-topologysegment.yml:2
ok: [ipaserver.test.local]
META: ran handlers

TASK [Delete topology segment] **************************************************************************************
task path: /root/delete-topologysegment.yml:7
ok: [ipaserver.test.local] => {"changed": false}
META: ran handlers
META: ran handlers

PLAY RECAP **********************************************************************************************************
ipaserver.test.local       : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0 

Actual results:
Not getting any error if the node does not exist.

Expected results:
it should provide an error if the node does not exist.

**Comment by t-woerner** [comment]
Delete may not fail on a missing entry. This is a requirement for idempotency.
