### ISSUE TITLE
ipaclient_join references ipadiscovery, which doesn't exist as an Ansible module

### ISSUE THREAD

**Issue by andrewimeson** [freeipa/ansible-freeipa#1108]
The example for the `ipaclient_join` Ansible module shows an example using the results from ipadiscovery, but there are now examples of how to register this variable, nor does there seem to be an Ansible module for running ipadiscovery.

https://github.com/freeipa/ansible-freeipa/blob/8f9c344bc1adfc6eedc990f58b4b7752935a986f/roles/ipaclient/library/ipaclient_join.py#L119-L128

My use case is writing my own playbooks using the modules from Galaxy to join a server to FreeIPA with DNS autodiscovery.

I could do something with `community.general.dig` instead.

```jinja2
"{{ lookup('community.general.dig',
   '_ldap._tcp.' + freeipa_domain + './SRV', flat=0, wantlist=true) }}"
```

**Comment by rjeffman** [comment]
The role modules are not intended to be used externally and must only be used by the modules itself.
