### ISSUE TITLE
 can't use mazer collections with requirements.yml (yet)

### ISSUE THREAD

**Issue by RobVerduijn** [freeipa/ansible-freeipa#111]
Hello,

I've been googling to find a way to use the ansible-freeipa roles via a requirements.yml file
Sadly i've come up empty.

I've found these
https://github.com/ansible/mazer
https://github.com/ansible/ansible/pull/57106

And some mention about tech preview for tower.

But so far ansible-galaxy might support collections in ansible 2.9, I guess they will provide some solution in the form of an requirements.yml or something

I've yet to find an explanation on how to use mazer in combination with awx/tower (tech preview suggests it should work somehow)

Does anybody have some pointers on how to do this with requirements.yml  or a
other way ? (besides issueing the cli mazer command)

Rob

**Comment by RobVerduijn** [comment]
ofcourse 5 seconds after I post this I try one more google

**Comment by t-woerner** [comment]
There has been this on ansible-devel group: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ansible-devel/ChNFHsCTpno/oMs3vvpdCAAJ
Therefore `ansible-galaxy` command should have support for collections in 2.9. Ansible collections are rather new and the tools and documentation is WIP.

But we need to use Ansible collection for ansible-freeipa in galaxy to be able to provide several roles and also modules. Role collections are not supported any more.

**Comment by dawud** [comment]
@t-woerner closing this issue as [FreeIPA is already in Galaxy as a collection](https://galaxy.ansible.com/freeipa/ansible_freeipa).
