### ISSUE TITLE
ipareplica 'Env' object has no attribute 'realm'

### ISSUE THREAD

**Issue by jonathon2nd** [freeipa/ansible-freeipa#114]
I am attempting to set up an ipaserver and an ipareplica. Server is installed and running fine. I have tried many things and have printed debugging different ways. I am not able to figure out why I am getting this error. Trying to hard code it in ansible-freeipa/roles/ipareplica/tasks/install.yml does not work either.

Sorry if I have made a mistake, appreciate any help.

**ipareplicas.yml:**
ipaserver_domain: example.com
ipaserver_realm: EXAMPLE.COM
ipaadmin_password: "{{vault_ipaadmin_password}}" 
ipadm_password: "{{vault_ipa_directory_password}}" 
ipaserver_hostname: "ipaserver.example.com"

**log:**
[ipareplica.example.com] TASK: ipareplica : Install - Replica preparation (debug)> [ipareplica.example.com] TASK: ipareplica : Install - Replica preparation (debug)> fatal: [ipareplica.example.com]: FAILED! => {"changed": false, "module_stderr": "Shared connection to X.X.X.X closed.\r\n", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/home/user/.ansible/tmp/ansible-tmp-1565391425.61-123383375333536/AnsiballZ_ipareplica_prepare.py\", line 262, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/user/.ansible/tmp/ansible-tmp-1565391425.61-123383375333536/AnsiballZ_ipareplica_prepare.py\", line 252, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/user/.ansible/tmp/ansible-tmp-1565391425.61-123383375333536/AnsiballZ_ipareplica_prepare.py\", line 120, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/tmp/ansible_ipareplica_prepare_payload_x3Wjlf/__main__.py\", line 2068, in <module>\r\n  File \"/tmp/ansible_ipareplica_prepare_payload_x3Wjlf/__main__.py\", line 1620, in main\r\nAttributeError: **'Env' object has no attribute 'realm'**\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
p task.args
[ipareplica.example.com] TASK: ipareplica : Install - Replica preparation (debug)> {'_ansible_check_mode': False,
 '_ansible_debug': False,
 '_ansible_diff': False,
 '_ansible_keep_remote_files': True,
 '_ansible_module_name': u'ipareplica_prepare',
 '_ansible_no_log': False,
 '_ansible_remote_tmp': u'~/.ansible/tmp',
 '_ansible_selinux_special_fs': ['fuse', 'nfs', 'vboxsf', 'ramfs', '9p'],
 '_ansible_shell_executable': u'/bin/sh',
 '_ansible_socket': None,
 '_ansible_string_conversion_action': u'warn',
 '_ansible_syslog_facility': u'LOG_USER',
 '_ansible_tmpdir': u'/home/user/.ansible/tmp/ansible-tmp-1565391425.61-123383375333536/',
 '_ansible_verbosity': 0,
 '_ansible_version': '2.8.2',
 u'allow_zone_overlap': False,
 u'auto_forwarders': False,
 u'auto_reverse': False,
 u'ca_cert_files': [],
 u'dirsrv_cert_files': [],
 u'domain': u'example.com',
 u'enable_compat': False,
 u'force_join': False,
 u'forwarders': [],
 u'hostname': u'ipareplica.example.com',
 u'http_cert_files': [],
 u'ip_addresses': [],
 u'mkhomedir': False,
 u'no_dns_sshfp': False,
 u'no_dnssec_validation': False,
 u'no_forwarders': False,
 u'no_host_dns': False,
 u'no_ntp': False,
 u'no_reverse': False,
 u'no_ssh': False,
 u'no_sshd': False,
 u'password': u'XXXXXXXXXXXXX',
 u'pkinit_cert_files': [],
 u'principal': u'admin',
 **u'realm': u'EXAMPLE.COM',**
 u'reverse_zones': [],
 u'server': u'ipaserver.example.com',
 u'setup_adtrust': False,
 u'setup_ca': False,
 u'setup_dns': False,
 u'setup_kra': False,
 u'skip_conncheck': False,
 u'ssh_trust_dns': False}

**Comment by t-woerner** [comment]
Which IPA version are you using? If env.realm is not there it means that the connection failed in the fist place. The question is: Why is there no error about the failed connection?

**Comment by jirib** [comment]
I got the the same. I'm using 4.6.4. on CentOS 7.

```
TASK [freeipa/ansible-freeipa/roles/ipareplica : Install - Replica preparation] ***********************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'Env' object has no attribute 'realm'
fatal: [ipa3.example.com]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_ipareplica_prepare_payload_HlXjXp/ansible_ipareplica_prepare_payload.zip/ansible/modules/ipareplica_prepare.py\", line 2068, in <module>\n  File \"/tmp/ansible_ipareplica_prepare_payload_HlXjXp/ansible_ipareplica_prepare_payload.zip/ansible/modules/ipareplica_prepare.py\", line 1620, in main\nAttributeError: 'Env' object has no attribute 'realm'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
[ipa3.example.com] TASK: freeipa/ansible-freeipa/roles/ipareplica : Install - Replica preparation (debug)> p task.args
{'_ansible_check_mode': False,
 '_ansible_debug': False,
 '_ansible_diff': False,
 '_ansible_keep_remote_files': False,
 '_ansible_module_name': 'ipareplica_prepare',
 '_ansible_no_log': False,
 '_ansible_remote_tmp': '~/.ansible/tmp',
 '_ansible_selinux_special_fs': ['fuse',
				 'nfs',
				 'vboxsf',
				 'ramfs',
				 '9p',
				 'vfat'],
 '_ansible_shell_executable': '/bin/sh',
 '_ansible_socket': None,
 '_ansible_string_conversion_action': 'warn',
 '_ansible_syslog_facility': 'LOG_USER',
 '_ansible_tmpdir': None,
 '_ansible_verbosity': 0,
 '_ansible_version': '2.9.3',
 'allow_zone_overlap': False,
 'auto_forwarders': False,
 'auto_reverse': False,
 'ca_cert_files': [],
 'dirsrv_cert_files': [],
 'domain': example.com',
 'enable_compat': False,
 'force_join': False,
 'forwarders': [],
 'hostname': 'ipa3.example.com',
 'http_cert_files': [],
 'ip_addresses': [],
 'mkhomedir': False,
 'no_dns_sshfp': False,
 'no_dnssec_validation': False,
 'no_forwarders': False,
 'no_host_dns': False,
 'no_ntp': False,
 'no_reverse': False,
 'no_ssh': False,
 'no_sshd': False,
 'password': '***censored***',
 'pkinit_cert_files': [],
 'principal': 'admin',
 'realm': 'EXAMPLE.COM',
 'reverse_zones': [],
 'server': 'ipa1.example.com',
 'setup_adtrust': False,
 'setup_ca': False,
 'setup_dns': False,
 'setup_kra': False,
 'skip_conncheck': False,
 'ssh_trust_dns': False}
[ipa3.example.com] TASK: freeipa/ansible-freeipa/roles/ipareplica : Install - Replica preparation (debug)>
```

**Comment by jirib** [comment]
@jonathon2nd my issue was related to disabled ipaadmin_principal account. Then I discovered missing DNS entries for new replica. After correcting these this task passed successfully.

**Comment by t-woerner** [comment]
Closing this issue.
