### ISSUE TITLE
ipareplica : Install - Setup DNS task fails with AttributeError: 'AnsibleModuleLog' object has no attribute 'isatty'

### ISSUE THREAD

**Issue by RobVerduijn** [freeipa/ansible-freeipa#117]
ipareplica : Install - Setup DNS task fails with AttributeError: 'AnsibleModuleLog' object has no attribute 'isatty'

Any idea where that comes from ?
Rob

**Comment by t-woerner** [comment]
No, not so far. There is no `isatty` call in ansible-freeipa at all. Do you have a traceback?

**Comment by RobVerduijn** [comment]
Hi,
It took some digging but here it is

Traceback (most recent call last):
  File \"<stdin>\", line 114, in <module>
  File \"<stdin>\", line 106, in _ansiballz_main
  File \"<stdin>\", line 49, in invoke_module
  File \"/usr/lib64/python3.6/imp.py\", line 235, in load_module
    return load_source(name, filename, file)
  File \"/usr/lib64/python3.6/imp.py\", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File \"<frozen importlib._bootstrap>\", line 618, in _exec
  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module
  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed
  File \"/tmp/ansible_ipareplica_setup_dns_payload_t7_r30p5/__main__.py\", line 191, in <module>
  File \"/tmp/ansible_ipareplica_setup_dns_payload_t7_r30p5/__main__.py\", line 180, in main
  File \"/usr/lib/python3.6/site-packages/ipaserver/install/dns.py\", line 381, in install
    bind.check_global_configuration()
  File \"/usr/lib/python3.6/site-packages/ipaserver/install/bindinstance.py\", line 1192, in check_global_configuration
    reverse=False)
  File \"/usr/lib/python3.6/site-packages/ipalib/frontend.py\", line 1086, in output_for_cli
    textui.print_entry(result, order, labels, flags, print_all)
  File \"/usr/lib/python3.6/site-packages/ipalib/cli.py\", line 425, in print_entry
    label, value, format, indent, one_value_per_line
  File \"/usr/lib/python3.6/site-packages/ipalib/cli.py\", line 336, in print_attribute
    line_len = self.get_tty_width()
  File \"/usr/lib/python3.6/site-packages/ipalib/cli.py\", line 112, in get_tty_width
    if sys.stdout.isatty():
AttributeError: 'AnsibleModuleLog' object has no attribute 'isatty'

**Comment by RobVerduijn** [comment]
this ipa server is on rhel8
