### ISSUE TITLE
ipahost ignores update_dns when deleting host

### ISSUE THREAD

**Issue by RobVerduijn** [freeipa/ansible-freeipa#127]
Hello,

When using the ipahost module to delete a host from ipa and setting the update_dns option to true it only deletes the host from ipa. The dns entries (A and PTR) are not deleted.

Rob

**Comment by t-woerner** [comment]
The update_dns flag is simply not used for host_del right now. This needs to be fixed.

**Comment by RobVerduijn** [comment]
ofcourse the sshfp records  need to be updated as well

**Comment by t-woerner** [comment]
The update_dns flag is honored with version 0.1.8. If sshfp records are handled with host_del, then this should be fixed also. If this needs to be done additionally, then it is not.

**Comment by RobVerduijn** [comment]
works fine now
