### ISSUE TITLE
The ipaclient role misspells sssd

### ISSUE THREAD

**Issue by Aad-Jan** [freeipa/ansible-freeipa#145]
In the ipclient role the variables relating to sssd seem to be missing one 's'
ipassd_fixed_primary: no
ipassd_permit: no
ipassd_enable_dns_updates: no
ipassd_no_krb5_offline_passwords: no
ipassd_preserve_sssd: no

In the README.md the variables are spelled correctly.
The misspelling is consistent in the role so this isn't a bug

The DOCUMENTATION part in ipaclient/library/ipaclient_setup_sssd.py the module is spelled "ipaclient_setup_ssd". The EXAMPLE however is correct.

**Comment by t-woerner** [comment]
Oh my, you are right, all the sssd related settings in ipaclient are really missing an 's'. No one noticed this so far. This is really a bug and needs to be fixed in a compatible way.

**Comment by Aad-Jan** [comment]
Well, it may not look too pretty but either the correct vars could be added to the defaults/main.yml with the value of the incorrectly spelled var
ipassd_fixed_primary: no
...
ipa**s**ssd_fixed_primary: "{{ ipassd_fixed_primary }}"

or you could declare only the correctly spelled variables and assign them the value of the incorrectly spelled ones without declaring them and using a default.
ipa**s**ssd_fixed_primary: "{{ ipassd_fixed_primary | default('no') }}"
