### ISSUE TITLE
save_state is looking for 1 argument (2 given)

### ISSUE THREAD

**Issue by BrianMusson** [freeipa/ansible-freeipa#15]
Was receiving this error:
save_state(nscd, statestore)\r\nTypeError: save_state() takes exactly 1 argument (2 given)\r\n"

I got around it by modifying ibrary/ipanss.py to save_state(nscd) and save_state(nslcd)

**Comment by t-woerner** [comment]
Fixed in https://github.com/freeipa/ansible-freeipa/commit/9beb31bf5ca5d6039f1ec0b439ca9a128311b69f
