### ISSUE TITLE
issue with service

### ISSUE THREAD

**Issue by lnxart** [freeipa/ansible-freeipa#152]
Hello,

We are using FreeIPA version 4.6 and when we run the "ipagroup" module in our ansible playbook we got the following error:
"
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_ipagroup_payload_n5dijG/ansible_ipagroup_payload.zip/ansible_collections/freeipa/ansible_freeipa/plugins/module_utils/ansible_freeipa_module.py", line 100, in api_command
    return api.Command[command](name, **args)
  File "/usr/lib/python2.7/site-packages/ipalib/frontend.py", line 450, in __call__
    return self.__do_call(*args, **options)
  File "/usr/lib/python2.7/site-packages/ipalib/frontend.py", line 464, in __do_call
    params = self.args_options_2_params(*args, **options)
  File "/usr/lib/python2.7/site-packages/ipalib/frontend.py", line 531, in args_options_2_params
    params = dict(self.__options_2_params(options))
  File "/usr/lib/python2.7/site-packages/ipalib/frontend.py", line 564, in __options_2_params
    option=unused_keys.pop())

fatal: [server.domain.com]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "action": "member", 
            "description": null, 
            "external": null, 
            "gid": null, 
            "group": null, 
            "ipaadmin_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "ipaadmin_principal": "admin", 
            "name": [
                "appops"
            ], 
            "nomembers": null, 
            "nonposix": null, 
            "service": null, 
            "state": "present", 
            "user": [
                "test.testies"
            ]
        }
    }, 
    "msg": "group_add_member: Unknown option: service"
}
"

Could you please check the issue?

Kind Regards,

**Comment by t-woerner** [comment]
This has been fixed with https://github.com/freeipa/ansible-freeipa/commit/a4a15defa994a15759efa588615040284206b8a2
There will be a new ansible-freeipa release on Monday which will also provide the fix. The galaxy release should also be there on Monday or Tuesday.

**Comment by lnxart** [comment]
Thank you for your work to fix it. Please let me know when you will add this feature to ansible core module ipa_group as there is not an option to add a user to a group while we can only mention the new user.

**Comment by t-woerner** [comment]
The Ansible provided ipa_ modules are not part of ansible-freeipa - I am not maintaing these modules. The only thing that could be done would be to create an issue or a PR for this.

**Comment by lnxart** [comment]
Please update the Galaxy release.

**Comment by dawud** [comment]
@lnxart this repository automatically publishes tagged [releases](https://github.com/freeipa/ansible-freeipa/releases) to [Ansible Galaxy](https://galaxy.ansible.com/freeipa/ansible_freeipa).

The latest version being [0.1.8](https://github.com/freeipa/ansible-freeipa/releases/tag/v0.1.8).

Please open a new issue if you can reproduce the problem with the `ipagroup` module supplied by this collection.
