### ISSUE TITLE
Container-enabled Roles

### ISSUE THREAD

**Issue by LorbusChris** [freeipa/ansible-freeipa#16]
Hi Everyone,
I'd like to use ansible to connect to my freeipa container to configure it.
There's guidelines in place for such roles, they're called "container-enabled roles".

Would you consider making (some) roles here in this repo container-enabled? 

Cheers,
Chris

**Comment by t-woerner** [comment]
What is needed to make the roles container-enabled?

**Comment by LorbusChris** [comment]
I think it needs to contain a `meta/container.yml` file containing a service definition.

https://docs.ansible.com/ansible-container/roles/writing.html#writing-roles
https://docs.ansible.com/ansible-container/roles/galaxy.html#container-enabled-roles

**Comment by dawud** [comment]
With [ansible-container](https://github.com/ansible/ansible-container) in archived/deprecated state, this issue is no longer relevant.
