### ISSUE TITLE
There is no way to add a user to a group

### ISSUE THREAD

**Issue by yhal003** [freeipa/ansible-freeipa#165]
It would be useful to be able to add/remove a user to a group that is not managed by ansible. i.e. the equivalent of group-add-member

**Comment by rjeffman** [comment]
I'm not sure what you mean by 'a group not manage by ansible', but you can add users to groups much like group-add-member.

Check the example playbook at [add-user-to-group.yml](https://github.com/freeipa/ansible-freeipa/blob/master/playbooks/user/add-user-to-group.yml)

**Comment by yhal003** [comment]
Sorry, I think I created an issue against a wrong project :). I was using this:
https://docs.ansible.com/ansible/latest/modules/ipa_group_module.html
But your module is different isn't it? Apologies :)
