### ISSUE TITLE
Problem with fonts and some resources

### ISSUE THREAD

**Issue by kozicpetar** [freeipa/ansible-freeipa#175]
Hi,

when I install server with ansible and login to ipa gui I can't see checkboxes and in console I get some error, some fonts don't exists.
I tried to install several times on fresh Linux but problem peresist.

Ubuntu 18.04 fresh installed server.

```GET /ipa/ui/js/libs/jquery-2.0.3.min.map HTTP/1.1" 404```

On this first picture when I click in checkbox alongside admin, a checkbox isn't checked, but disabled-buttons from upper right corner enable.

![Screen Shot 2019-12-18 at 3 57 37 PM](https://user-images.githubusercontent.com/53332414/71097015-9fab0480-21af-11ea-8171-2a0b06644303.png)

On this second picture you can see some font's missing.

![Screen Shot 2019-12-18 at 4 03 22 PM](https://user-images.githubusercontent.com/53332414/71097270-092b1300-21b0-11ea-8e43-48b1d07b56f8.png)

I tried with several browsers, same problem.
Any idea?

**Comment by t-woerner** [comment]
The roles in ansible-freeipa are depending on the normal installers and are installing the needed freeipa packages.
Is this issue only happening for you using the ipaserver role and not happening with the ipa-server-install command?

**Comment by kozicpetar** [comment]
I have error in both scenario.

I found issue maybe that can be put in ansible for Ubuntu 18.04

```apt install libjs-scriptaculous```

The installed code expects fontawesome, not font-awesome in the truetype directory.
```
cd /usr/share/fonts/truetype
ln -s font-awesome /usr/share/fonts/truetype/fontawesome
```

![Screen Shot 2019-12-18 at 4 40 30 PM](https://user-images.githubusercontent.com/53332414/71100328-1f879d80-21b5-11ea-995c-39408fa71d60.png)
