### ISSUE TITLE
How to set up firewalld zones?

### ISSUE THREAD

**Issue by Hoeze** [freeipa/ansible-freeipa#177]
Hi, I'd like to set up zones for the freeipa server because the server has an interface with public IP and another interface within our private network.

The command I used to run is the following:
```bash
firewall-cmd --permanent --new-zone=LAN
firewall-cmd --reload
firewall-cmd --permanent --zone=gagneurLAN --add-service=ssh
firewall-cmd --permanent --zone=gagneurLAN --add-service={http,https}
firewall-cmd --permanent --zone=gagneurLAN --add-service={kerberos,kpasswd}
firewall-cmd --permanent --zone=gagneurLAN --add-service={ldap,ldaps}
firewall-cmd --permanent --zone=gagneurLAN --add-service=ntp
firewall-cmd --permanent --zone=gagneurLAN --add-port=53/tcp --add-port=53/udp
firewall-cmd --zone=LAN --change-interface=enp0s8
```

How can I accomplish this with ansible-freeipa?

**Comment by rjeffman** [comment]
To configure firewalld you might try the Ansible firewalld module.

Take a look at https://docs.ansible.com/ansible/latest/modules/firewalld_module.html

**Comment by t-woerner** [comment]
I think we should be able to add variables like `ipaserver_firewalld_zone` and `ipareplica_firewalld_zone` to use an existing zone to enable the needed ipa services.

**Comment by rjeffman** [comment]
As PR #389 was merged, fixing this issue I'm closing it. If it still does not fix your issue, please, comment and reopen.
