### ISSUE TITLE
Install freeipa ansible collection error

### ISSUE THREAD

**Issue by foxpluto** [freeipa/ansible-freeipa#180]
Dear developers,

I am trying to install the freeipa collection for ansible but I have a strange error in return:
```
MacBook-Pro:roles fox$ ansible-galaxy collection install freeipa.ansible_freeipa
Process install dependency map
ERROR! Cannot meet requirement * for dependency freeipa.ansible_freeipa from source 'https://galaxy.ansible.com/api/'. Available versions before last requirement added:
Requirements from:
	base - 'freeipa.ansible_freeipa:*'
```
my version of ansible is:
```
MacBook-Pro:roles fox$ ansible-galaxy --version
ansible-galaxy 2.9.2
  config file = /Users/fox/.ansible.cfg
  configured module search path = ['/Users/fox/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.2/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-galaxy
  python version = 3.7.6 (default, Dec 30 2019, 19:38:26) [Clang 11.0.0 (clang-1100.0.33.16)]
```
The installation of the collection with Ansible 2.9 shouldn't be supported? 

Regards,
Stefano

**Comment by dawud** [comment]
This is a known issue with how the Galaxy client parses SemVer data.
It's being tracked in the main [ansible repository](https://github.com/ansible/ansible/issues/64905).

For now, you can workaround this by explicitly setting a version.
You can check the latest version available directly in [Galaxy](https://galaxy.ansible.com/freeipa/ansible_freeipa).

```bash
ansible-galaxy collection install freeipa.ansible_freeipa:0.1.8-1
Process install dependency map
Starting collection install process
Installing 'freeipa.ansible_freeipa:0.1.8-1' to '/home/david/.ansible/collections/ansible_collections/freeipa/ansible_freeipa'
```

**Comment by dawud** [comment]
@foxpluto @t-woerner OK to close this issue with the WA mentioned above?

Thanks!

**Comment by foxpluto** [comment]
Thanks for the suggestion!

Yes, ok to close.

Regards,
S.

Il lun 6 gen 2020, 20:50 David Sastre Medina <notifications@github.com> ha
scritto:
