### ISSUE TITLE
Bulk add of rhel machines to IdM failing with error

### ISSUE THREAD

**Issue by AbhijeetTilawat** [freeipa/ansible-freeipa#193]
Hi Team,

M trying to add rhel7.4 machines as clients in an IdM server through play book install-client.yml but it is getting failed with below error when it comes to task "TASK [ipaclient : Install - IPA client test]" in /root/ansible-freeipa-master/roles/ipaclient/tasks/install.yml. Tasks above then this one runs successfully but fails when it reaches "ipaclient : Install - IPA client test" with below error:
--------------------------
TASK [ipaclient : Install - IPA client test] ***************************************************************************************************************************
task path: /root/ansible-freeipa-master/roles/ipaclient/tasks/install.yml:33
fatal: [10.70.231.117]: FAILED! => {"changed": false, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1579861141.89-45757400858769/AnsiballZ_ipaclient_test.py\", line 113, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1579861141.89-45757400858769/AnsiballZ_ipaclient_test.py\", line 105, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1579861141.89-45757400858769/AnsiballZ_ipaclient_test.py\", line 48, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/tmp/ansible_ipaclient_test_payload_bgKUKL/__main__.py\", line 932, in <module>\r\n  File \"/tmp/ansible_ipaclient_test_payload_bgKUKL/__main__.py\", line 875, in main\r\nTypeError: info() takes at least 2 arguments (1 given)\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
fatal: [10.70.231.110]: FAILED! => {"changed": false, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1579861141.82-202518387711092/AnsiballZ_ipaclient_test.py\", line 113, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1579861141.82-202518387711092/AnsiballZ_ipaclient_test.py\", line 105, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1579861141.82-202518387711092/AnsiballZ_ipaclient_test.py\", line 48, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/tmp/ansible_ipaclient_test_payload_YHZRFO/__main__.py\", line 932, in <module>\r\n  File \"/tmp/ansible_ipaclient_test_payload_YHZRFO/__main__.py\", line 875, in main\r\nTypeError: info() takes at least 2 arguments (1 given)\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
        to retry, use: --limit @/root/install-client.retry

PLAY RECAP *************************************************************************************************************************************************************
10.70.231.110              : ok=5    changed=0    unreachable=0    failed=1
10.70.231.117              : ok=5    changed=0    unreachable=0    failed=1
--------------------------

below is the attached complete output of ansible playbook run:  
[complete-output.txt](https://github.com/freeipa/ansible-freeipa/files/4107988/complete-output.txt)

Output of "ansible --version"
ansible 2.7.15
  config file = /root/ansible.cfg
  configured module search path = [u'/root/ansible-freeipa-master/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

Please help!! We need to add around 800 Linux(RHEL 6 and 7) machines to IdM server. We cannot do it manually!

**Comment by AbhijeetTilawat** [comment]
Attached output of ansible playbook run is in verbose mode - "-vvvv"

**Comment by rjeffman** [comment]
It might happen when using IP addresses instead of FQDN. Is it what you are using?

**Comment by AbhijeetTilawat** [comment]
Hello rjeffman,

Thanks for your help and yes, we were using IP addresses of machines to add instead of hostnames. Changing IP's to hostnames in inventory file  did allowed us to progress but now, we are stuck at "TASK [ipaclient : Install - Get One-Time Password for client enrollment]" with below error:
-----------
fatal: [server-y.linuxsystems.local]: UNREACHABLE! => {
    "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result",
    "changed": false
}
-----------

For testing purpose, we limited our inventory to just one server (server-y) in above output. 

Below is the complete playbook run output with -vvvv :

[ansible-output.txt](https://github.com/freeipa/ansible-freeipa/files/4111658/ansible-output.txt)
-----------

**Comment by AbhijeetTilawat** [comment]
Hi,

This issue can be closed as we were able to add hosts after commenting ipaclient_use_otp method to enroll clients in IdM domain.

Thanks for help!!
