### ISSUE TITLE
Host module is not working with FreeIPA 4.4.0

### ISSUE THREAD

**Issue by rjeffman** [freeipa/ansible-freeipa#211]
Runing the playbook at `playbooks/host/host-present.yml` against a CentOS 7.3 with IPA 4.4.0, I observe the following error:

```
TASK [Ensure host is present] ********************************************************
fatal: [centos73.ipademo.local]: FAILED! => {"changed": false, "msg": "invalid 'dnszoneidnsname': only master zones can contain records"}
```
The same error occur when ensuring a host is absent, when it is already absent.

Find attached the execution of the playbook with verbose mode `-vvv`.

[host-present.log](https://github.com/freeipa/ansible-freeipa/files/4257084/host-present.log)

**Comment by rafasgj** [comment]
I tried with both the current master tree (commit 200eb30) and with release 0.1.8, using macOS 10.15.3, and vagrant CentOS 8 vm, and install-server.yml worked fine.
 
Some useful information: `ansible --version` I have `ansible 2.9.5`,  `ansible python module location = /Users/rafael/Library/Python/3.7/lib/python/site-packages/ansible`, `executable location = /Users/rafael/Library/Python/3.7/bin/ansible` and `python version = 3.7.3 (default, Dec 13 2019, 19:58:14) [Clang 11.0.0 (clang-1100.0.33.17)]`.

**Comment by rjeffman** [comment]
Created a clean installation, and the issue is not reproducible there. After trying to find out what was happening on the broken instance, the error stopped to reproduce.

Closing as not reproduced.
