### ISSUE TITLE
Is it possible to set system-configuration issues via Ansible?

### ISSUE THREAD

**Issue by str8edgedave** [freeipa/ansible-freeipa#221]
Its it possible to set the following configuration items (in IPA Server -> Configuration) via Ansible during setup?

- Default e-mail domain
- Domain resolution order 
- Default users group
- Home directory base
- Default shell
- Password Expiration Notification (days) <- I think I know how to do this.

Thanks,
David

**Comment by rjeffman** [comment]
Currently, not with ansible-freeipa, although support is planned.

**Comment by t-woerner** [comment]
You can set these after deploying the server using the config module: https://github.com/freeipa/ansible-freeipa/blob/master/README-config.md
