### ISSUE TITLE
Installing with External Certificate

### ISSUE THREAD

**Issue by farazbyk** [freeipa/ansible-freeipa#225]
Hello,
I'm getting below error when installing external certificate, setup-ca= no and external-ca=yes , dns=no and firewall=no
Can you please help me to setup with existing external certificate ?
PlayBook:
---
- name: Playbook to configure IPA server step3
  hosts: ipaserver
  vars_files: ../vars/freeipa-adm.yml
  become: true
  vars:
    - ipaserver_external_ca: yes
    - ipaserver_external_cert_files: "/root/chain.crt"

  pre_tasks:
  - name: Copy "{{ groups.ipaserver[0] + '-chain.crt' }}" to /root/chain.crt on node
    copy:
      src: "chain.crt" 
      dest: "/root/chain.crt"
      force: yes

  roles:
  - role: ../roles/airtime.freeipa/ipaserver
    state: present

TASK [../roles/airtime.freeipa/ipaserver : Install - Use new master password] ********************************************************************************
ok: [sg.abc.com]

TASK [../roles/airtime.freeipa/ipaserver : Install - Server preparation] *************************************************************************************
fatal: [sg.abc.com]: FAILED! => {"changed": false, "msg": "CA is not installed yet. To install with an external CA is a two-stage process.\nFirst run the installer with --external-ca."}

**Comment by rjeffman** [comment]
The installation with an external CA is a two step process, and the script you gave is similar to the second step.

[In the server role documentation](https://github.com/freeipa/ansible-freeipa/tree/master/roles/ipaserver), in the sixth example you'll find the first of the two steps, and after it the second step (similar to your script).

If you ran the first step before, we need some more information to see what's going on, like running `ansible-playbook` with `-vvv`.

**Comment by t-woerner** [comment]
You are setting `ipaserver_external_ca` and `ipaserver_external_cert_files` at the same time. `ipaserver_external_ca` only should be set in the first step and `ipaserver_external_cert_files` only in the second step of the IPA server deployment.

Please have a look at `https://github.com/freeipa/ansible-freeipa/blob/master/tests/external-signed-ca-with-manual-copy/install-server-with-external-ca-with-manual-copy.yml` for an example.
