### ISSUE TITLE
Module to create auto-membership rules

### ISSUE THREAD

**Issue by itcultus** [freeipa/ansible-freeipa#277]
We provision our hosts from an Integrated with IdM Satellite server. 
It would be create to have a module that configures auto-membership rules for Hosts and Users.

**Comment by Wolskie** [comment]
Have also come across the need for auto-membership rules. I think I will try implement this functionality.

**Comment by rjeffman** [comment]
PR #486 aims to provide this functionality.

**Comment by rjeffman** [comment]
PR #486, which provides automembership management has been merged.
