### ISSUE TITLE
Adding external CAs

### ISSUE THREAD

**Issue by diniguezcabrera** [freeipa/ansible-freeipa#278]
I checked the documentation, and found the steps described to use an external CA

`Playbook to configure IPA server step1`
`
Playbook to configure IPA server step3`

I'm missing a step 2, is this a typo?

Regarding the steps, is the order strict? Can I exec both steps in the same playbook?

I'm also trying to install the CA of my company in the freeipa server. I have tried to install it directly in the apache server (httpd, the server is running on centos 8) but with no result and lots of errors in the error_log.

`ipa: INFO: 401 Unauthorized: HTTPSConnectionPool(host='freeipa1.domain.com', port=443): Max retries exceeded with url: /ipa/session/cookie (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)'),))`

So I read the documentation and saw the variables to add the certificate of my company, which has:

- cert.crt
- cert.key
- chain.crt

and I still don't understand how to add the certificate. I'm still doing tests, installing and uninstalling the server so any method is ok by me.

**Comment by t-woerner** [comment]
Step 2 (from https://github.com/freeipa/ansible-freeipa/blob/master/roles/ipaserver/README.md):
- Sign with CA: This is up to you
- Copy <ipaserver hostname>-chain.crt to the IPA server and continue with installation of the primary.

**Comment by t-woerner** [comment]
Here are example playbooks for this: https://github.com/freeipa/ansible-freeipa/tree/master/tests/external-signed-ca-with-manual-copy and  https://github.com/freeipa/ansible-freeipa/tree/master/tests/external-signed-ca-with-automatic-copy
For these tests a new CA is generated to sign the certificate request.

**Comment by t-woerner** [comment]
CERTIFICATE_VERIFY_FAILED means that there is something wrong with your certificate. Please check the log files for more information.
