### ISSUE TITLE
No ipaplatform available for "macos"

### ISSUE THREAD

**Issue by piyat** [freeipa/ansible-freeipa#293]
Dear developers,

I was hoping to test out the ipagroup module as an alternative to the upstream ipa_group module but I am having difficulty running it from my control host (my laptop, macOS). If you've any pointers it would be greatly appreciated. This might be a really simple one like "macos is not supported" (hope not though 👍 ).

I interpreted the supported distributions section in the README to mean the supported distros for installing IPA software onto, but assumed I could run the modules from anywhere that ansible can be installed.

**Versions**
Control Host: MacOS Mojave
Ansible: 2.9.9
Python: 3.7.5

Target host: RHEL 7.7
FreeIPA: 4.5.4

**Installation** 

Per the README:

- `ansible-galaxy collection install freeipa.ansible_freeipa` <- Succeeded

- Installed gssapi with pip3 <- Succeeded (installed gssapi-1.6.5)
- Configured inventory.
- Wrote simple playbook to create one group including:

`  collections:`
`    - freeipa.ansible_freeipa`

**Initial Errors/Misconfiguration**

- No module named `ipalib`
- Installed ipalib with pip3 <- Succeeded (installed ipalib-4.8.6)
- ImportError: libldap_r shared library missing
- Installed python-ldap <- Succeeded (installed python-ldap-3.2.0)

**Current Error**

>   File "/usr/local/lib/python3.7/site-packages/ipaplatform/osinfo.py", line 209, in platform
    ', '.join(self.platform_ids)))
ImportError: No ipaplatform available for "macos"

From lines 197-209 in `osinfo.py` I can see that an attempt is made to import a module for my platform macos from the parent dir, something like:

`importlib.import_module('ipaplatform.macos')`

Which doesn't exist. I ran this command with macos substituted for a module which did exist, and that worked e.g:

> >>> importlib.import_module('ipaplatform.debian')
<module 'ipaplatform.debian' from ...>

Unfortunately I'm really stuck on this one and I haven't made much progress with it this evening so I am reaching out for any guidance which would be really helpful, even to tell me it is not gonna work!

Thank you.

**Comment by t-woerner** [comment]
Contrary to the `ipa_group` module, most of the modules in ansible-freeipa need to be executed on a replica or server that belongs to the domain. The exception is the vault module.

The modules are accessing the API directly and are using the server context to speed up processing. It would be possible to also execute the modules on client machines, when the context in the api_connect function is set to something like `anisble-freeipa` or `client` - like it is done in the vault module. It is planned to have a parameter for this in the future.

Please set hosts in your playbook to the primary master or a replica in your domain.

**Comment by piyat** [comment]
Thanks for the reply, is it possible to get definitions of the inventory variables I need? I wasn't able to get this to run per your advice so I think I've supplied an incorrect value somewhere.

**Comment by t-woerner** [comment]
Sure, for general variables, please have a look at https://github.com/freeipa/ansible-freeipa#ansible-inventory-file or for server specific at https://github.com/freeipa/ansible-freeipa/blob/master/roles/ipaserver/README.md

**Comment by piyat** [comment]
Hi Thomas - apologies, I never got back to you to say thanks, this helped me!

**Comment by t-woerner** [comment]
No problem, you are welcome :-)
