### ISSUE TITLE
IPA replica installation failure - DS enabled SSL

### ISSUE THREAD

**Issue by Yalafeg** [freeipa/ansible-freeipa#314]
Hello,

While trying to install the ipareplica, I am getting the below error under the section "TASK [ipareplica : Install - DS enable SSL]": 

Error in mode debug:

line 826, in __enable_ssl\r\n    dsdb.create_from_pkcs12(self.pkcs12_info[0], self.pkcs12_info[1],\r\nIndexError: list index out of range\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1

Error from log file:

DEBUG   [1/3]: configuring TLS for DS instance
DEBUG Loading Index file from '/var/lib/ipa/sysrestore/sysrestore.index'
DEBUG Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ipaserver/install/service.py", line 603, in start_creation
    run_step(full_msg, method)
  File "/usr/lib/python3.6/site-packages/ipaserver/install/service.py", line 589, in run_step
    method()
  File "/usr/lib/python3.6/site-packages/ipaserver/install/dsinstance.py", line 826, in __enable_ssl
    dsdb.create_from_pkcs12(self.pkcs12_info[0], self.pkcs12_info[1],
IndexError: list index out of range

DEBUG   [error] IndexError: list index out of range

Kindly note that I was able to install the ipareplica successfully using command line (ipa-replica-install) and without any error.

Noting that I am installing the ipareplica without external certificate and without any additional configuration.

Information about the environment:

Ansible version: 2.8 / 2.9

IPA replica server Redhat 8, with 8 GB  RAM

Regards,

**Comment by t-woerner** [comment]
This has been fixed with https://github.com/freeipa/ansible-freeipa/pull/313
I plan to create a new release tomorrow.

**Comment by Yalafeg** [comment]
Hello,

Thank you, the problem is solved after modifying both install.yml files.

But, I am getting now a new error during the task "[ipareplica : Install - Setup kra] ". 

HTTPError: 404 Client Error: Not Found for url: https://xxx/ipa/keys/ca/auditSigningCert%20cert-pki-kra

DEBUG Starting new HTTPS connection (1): xxx:443
DEBUG https://xxx:443 "GET /ipa/keys/ca/auditSigningCert%20cert-pki-kra?type=


Kindly note that the KRA is installed and enabled successfully on the ipaserver.

Regards,

**Comment by t-woerner** [comment]
What have you enabled in the configuration for the replica?

**Comment by Yalafeg** [comment]
Hello,

Below are the values for the replica

ipaservers: 'server.example.com'
ipareplicas: 'replica.example.com'
ipaclient_domain: 'example.com'
ipaadmin_password: 'ADMPassword1'
ipareplica_domain: 'example.com'
ipaserver_realm: 'EXAMPLE.COM'
ipaserver_hostname: 'replica.example.com'
ipaadmin_principal: 'admin'
ipadm_password: 'MySecretPassword234'
ipareplica_realm: 'EXAMPLE.COM'
ipareplica_setup_adtrust: true
ipareplica_setup_kra: true
ipareplica_setup_ca: true
ipareplica_servers: 'server.example.com'
ipaserver_domain: 'example.com'
ipaclient_force_join: true

**Comment by t-woerner** [comment]
Which distribution (and IPA version) are you using?

**Comment by Yalafeg** [comment]
Redhat 8 and IPA version 4.8

**Comment by t-woerner** [comment]
Have you been using this inventory to deploy the server also? `ipaserver_hostname: 'replica.example.com'` is not good.

**Comment by Yalafeg** [comment]
Below is the inventory of the server: 

ipaserver: 'server.example.com'
ipadm_password: 'MySecretPassword234'
ipaadmin_password: 'ADMPassword1'
ipaserver_domain: 'example.com'
ipaserver_realm: 'EXAMPLE.COM'
ipaadmin_principal: 'admin'
ipaserver_hostname: 'server.example.com'
ipaserver_setup_adtrust: true
ipaserver_setup_kra: true

**Comment by t-woerner** [comment]
I am able to reproduce this issue. It will need investigation.

As a work a round, you could try to deploy the replica without kra and enable this afterwards with the `ipa-kra-install` command on the replica. That was working for me.

I think I need to wait with the new release till this issue is solved also.

**Comment by Yalafeg** [comment]
Noted, thank you
