### ISSUE TITLE
what is the best workaround for ansible bug #68361 ?

### ISSUE THREAD

**Issue by RobVerduijn** [freeipa/ansible-freeipa#315]
Hello,

After trying to install freeipa server with the ansible-freeipa collection for a couple days I found out I was being bitten by this bug:
https://github.com/ansible/ansible/issues/68361

You obviously already know this one and you can't help it because it is an ansible bug,
Since it seems that this one is going to take a while before it is applied in a stable release (or backported to 2.9)
what would you recommend as a workaround for this one ?
(besides manually applying the patch mentioned in the post)

Rob

**Comment by t-woerner** [comment]
Ansible 2.10 should provide a fix for this issue. I have not been able to test this though.

**Comment by t-woerner** [comment]
A possible workaround for now is to install ipa-server packages also on the controller. Then ansible is able to load the modules on the controller to find out which modules need to be transferred to the node.

**Comment by t-woerner** [comment]
Only the collection is affected by this. You can also use the RPM that is part of RHEL-8 and Fedora it is installing the roles and plugins into the default ansible locations for roles and plugins. You can use the roles and plugins from the ansible-[freeipa releases](https://github.com/freeipa/ansible-freeipa/releases). Please have a look at https://github.com/freeipa/ansible-freeipa#how-to-use-ansible-freeipa and ignore the galaxy section there.

**Comment by RobVerduijn** [comment]
Thanx,

I'll definitely consider your suggestions and which one to use.
Let's hope ansible 2.10 doesn't mis it's roadmap release date by much, which is next month
https://docs.ansible.com/ansible/devel/roadmap/ROADMAP_2_10.html

Rob

**Comment by RobVerduijn** [comment]
This bug is back again

Rob

**Comment by rjeffman** [comment]
@RobVerduijn, the bug never gone away. It is an Ansible 2.9 issue with collections.
