### ISSUE TITLE
ipaserver_setup_ca.py error

### ISSUE THREAD

**Issue by pyguy** [freeipa/ansible-freeipa#32]
I get this error while running install-server.yml playbook

 `"module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_k_kngm/ansible_module_ipaserver_setup_ca.py\", line 236, in <module>\r\n    main()\r\n  File \"/tmp/ansible_k_kngm/ansible_module_ipaserver_setup_ca.py\", line 192, in main\r\n    custodia = custodiainstance.get_custodia_instance(\r\nAttributeError: 'module' object has no attribute 'get_custodia_instance'\r\n", "msg": "MODULE FAILURE", "rc": 1}`

Am I missing a module?

**Comment by t-woerner** [comment]
Ok, the latest applied pull requests should solve this for you right now. The use of version numbers to decide if custodia needs to be used the new way was bad as some patches have been back-ported to the EL-7 IPA package.
Therefore I will push a new commit in where this decision is done dynamically according to the availability of ```get_custodia_instance``` in ```custodiainstance```.
