### ISSUE TITLE
Last tag is quite old

### ISSUE THREAD

**Issue by Thulium-Drake** [freeipa/ansible-freeipa#346]
Hi guys,

It seems there are quite some fixes and other work missing from Galaxy (and other sources that rely on tagged releases, as 0.1.12 is from june).

Any chance there will be a new tag soon-ish?

Cheers!

**Comment by rjeffman** [comment]
@Thulium-Drake, yes, there is a new release right after the corner. I can't promise a date, but it should be pretty soon.

**Comment by rjeffman** [comment]
@Thulium-Drake, version 0.2.0 is available on Ansible Galaxy.

I'm closing this issue, as a new release was made. If you think it is not enough, please, reopen and let us know what else can be done.
