### ISSUE TITLE
No package matching 'krb5-workstation' is available

### ISSUE THREAD

**Issue by pyguy** [freeipa/ansible-freeipa#35]
getting this error while running freeipa client playbook on ubuntu.
{"changed": false, "item": "krb5-workstation", "msg": "No package matching 'krb5-workstation' is available"}

**Comment by t-woerner** [comment]
Which distribution are you using?

**Comment by pyguy** [comment]
Ubuntu

**Comment by t-woerner** [comment]
O.k. there is a pull request to add ubuntu support. I will do the requested changes myself now. Ubunto/debian support should be available then.

**Comment by t-woerner** [comment]
This should be fixed with commit b2583f70782ad91786cb0b6f1c44367b3cf635f2

    Ubuntu support added (partly pick from pyguy)
    
    This is a partly pick of the changes done by pyguy for pull request #28.
    The unrelated changed on inventory files have been removed and the change
    to the README has been adapted to use the "Supported Distributions" section.
    
    The original commits by pyguy in https://github.com/pyguy/ansible-freeipa
    are:
    
    commit 1ed1fa845eafd69432b1fd1fc8e5329e4991e84a
    Author: pyguy <hr.josheghani@gmail.com>
    Date:   Mon Jun 25 17:17:31 2018 +0430
    
        Ubuntu Support added
    
    commit 9a4a7c84e4af20af27e814aba4fc2c6b8b35ec0f
    Author: pyguy <hr.josheghani@gmail.com>
    Date:   Sun Jun 24 10:58:07 2018 +0430
    
        Ubuntu support added

**Comment by amitkverma** [comment]
Replace `krb5-workstation` to `krb5-k5tls` for Ubuntu
