### ISSUE TITLE
configure ipa-client-install

### ISSUE THREAD

**Issue by pappu79** [freeipa/ansible-freeipa#352]
Hi Team,

I want to configure ipa-client-install in almost 500 linux machine. i want to run this command through ansible playbook. ipaclient module is not available. and my ansible version is 2.8.13 and python version python version = 2.7.5

**Comment by t-woerner** [comment]
There is no ipaclient module, there is an ipaclient role for client deployment. Please have a look at https://github.com/freeipa/ansible-freeipa/blob/master/roles/ipaclient/README.md for information how to use the role to deploy clients.
