### ISSUE TITLE
'options_obj' object has no attribute 'add_sids'

### ISSUE THREAD

**Issue by silanea** [freeipa/ansible-freeipa#36]
`Traceback (most recent call last):`
`  File \"/tmp/ansible_k4i2cvbx/ansible_module_ipaserver_test.py\", line 787, in <module>`
`    main()`
`  File \"/tmp/ansible_k4i2cvbx/ansible_module_ipaserver_test.py\", line 730, in main`
`    adtrust.install_check(False, options, api)`
`  File \"/usr/lib/python3.6/site-packages/ipaserver/install/adtrust.py\", line 408, in install_check`
`    if not options.add_sids:`
`AttributeError: 'options_obj' object has no attribute 'add_sids'`

Fedora Server 28, with the latest commit (b2583f7)

**Comment by t-woerner** [comment]
You have adtrust enabled, right?

**Comment by silanea** [comment]
@t-woerner You mean "ipaserver_setup_adtrust: yes", I presume? Yes, it is set.

**Comment by silanea** [comment]
And ever onward down the rabbit hole it goes. Result after revised patch:
`TASK [ipaserver : Install - Setup ADTRUST] ***************************************************************************************************************************************************************************************************
fatal: [lacedaemon]: FAILED! => {"changed": false, "module_stderr": "Shared connection to lacedaemon.cds-infra.de closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_5by0h0gv/ansible_module_ipaserver_setup_adtrust.py\", line 88, in <module>\r\n    main()\r\n  File \"/tmp/ansible_5by0h0gv/ansible_module_ipaserver_setup_adtrust.py\", line 76, in main\r\n    api_Backend_ldap2_connect(options.host_name, options.setup_ca)\r\nNameError: name 'api_Backend_ldap2_connect' is not defined\r\n", "msg": "MODULE FAILURE", "rc": 1}`

Missing dependency? dnf only gives me packages for LDAP and LDAP3 (python2-ldap, python3-ldap, python2-ldap3 and python3-ldap3).

**Comment by silanea** [comment]
@t-woerner is the patch I uploaded sufficient for you to merge, or would you prefer for me to file a proper PR?
