### ISSUE TITLE
ipahostgroup module needs missing python module ipaserver.plugins

### ISSUE THREAD

**Issue by timvy** [freeipa/ansible-freeipa#369]
Running a task to add a host to a hostgroup gives the error: 
` File "/usr/lib/python2.7/site-packages/ipalib/__init__.py", line 940, in packages
    import ipaserver.plugins
fatal: [ipaclient]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "action": "member",
            "description": null,
            "host": [
                "mcs-devtest-mvpbridge-1.be.vzbi.com"
            ],
            "hostgroup": null,
            "ipaadmin_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "ipaadmin_principal": "admin",
            "membermanager_group": null,
            "membermanager_user": null,
            "name": [
                "mcs-server"
            ],
            "nomembers": null,
            "state": "present"
        }
    },
    "msg": "No module named ipaserver.plugins"
}
`
ansible-playbook 2.9.9
  config file = /home/esadmin/tim/freeipa/ansible.cfg
  configured module search path = ['/home/esadmin/tim/freeipa/ansible_collections/freeipa/ansible_freeipa/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

controller is centos 8.2.2004
host is centos  7.8.2003, with Python 2.7.5 installed

**Comment by t-woerner** [comment]
How are you using the ipahostgroup module? Where are you running the module and how did you deploy the server?

**Comment by timvy** [comment]
I call the module in a playbook:

  - name: Add host to freeipa group
    ipahostgroup:
      ipaadmin_password: "{{ ipaadmin_password }}"
      name: "{{ hostgrp }}"
      host: "{{ ansible_facts['nodename'] }}"
      action: member

The ipa client has been installed via the ipaclient role from this collection, that works really well. The ipa server is an existing environment, not set up via ansible.

**Comment by t-woerner** [comment]
The management modules need to be executed on a server or replica as they are using the server context to speed up processing.

You could enable the execution of most modules also on clients by changing the default context in plugins/module_utils/ansible_freeipa_module.py in the api_connect function. It is planned to have a parameter for this in the future.

**Comment by timvy** [comment]
Aha, i did not know that I needed to run that on the server. Thanks for clarifying!
