### ISSUE TITLE
[RFE] Need a ipa_permission module

### ISSUE THREAD

**Issue by kresss** [freeipa/ansible-freeipa#377]
There should be a module for ipa_permission. 

For instance we configure our IPA system with the following command:

`ipa permission-mod  "System: Read User Standard Attributes" --includedattrs="employeenumber"`

**Comment by seocam** [comment]
Thanks for letting us know that it would be useful for you. We do have plans to implementing the module in the following months but unfortunately we don't have a exact date for that yet. 

If you want to give a shot and try to implement it your PR would be welcome, otherwise stay tuned :)

**Comment by rjeffman** [comment]
I'm closing this issue, as an ipapermission module was merged (#387).
