### ISSUE TITLE
IPA replica install fails on "DS enable SSL"

### ISSUE THREAD

**Issue by jswindle-rtn** [freeipa/ansible-freeipa#383]
What do I need to set to get replica to install? Is there something I'm missing in my configuration?

It throws a traceback. Looks like it is because  _dirsrv_pkcs12_info and _pkinit_pkcs12_info are both null.

Based upon the README.md I have minimum variables set to install a running replica.

variables set in env_specific.yml':
`ipaserver_domain: high.example.com
ipaserver_realm: HIGH.EXAMPLE.COM
ipaserver_hostname: admin.high.example.com
ipaserver_auto_forwarders: yes
ipaserver_no_forwarders: no
ipaserver_no_host_dns: true
ipaserver_setup_dns: yes
`
Playbook:
`- name: Playbook to configure IPA replicas
  hosts: ipareplicas
  become: true
  vars_files:
    - /opt/ansible/config/credentials.yml
    - /opt/ansible/config/env_specific.yml
  vars:
    - ipareplica_setup_ca: true
    - ipareplica_setup_dns: '{{ ipaserver_setup_dns }}'
    - ipareplica_auto_forwarders: '{{ ipaserver_auto_forwarders }}'
    - ipareplica_no_forwarders: '{{ ipaserver_no_forwarders }}'
    - ipareplica_no_host_dns: '{{ ipaserver_no_host_dns }}'
  pre_tasks:
    - name: Set ansible user umask to 0022
      lineinfile:
        path: /home/ansible/.bashrc
        line: umask 0022
        state: present
  roles:
  - role: ipareplica # role provided by ansible-freeipa
  post_tasks:
    - name: Remove ansible user umask 0022
      lineinfile:
        path: /home/ansible/.bashrc
        line: umask 0022
        state: absent
`
Running:
ansible-freeipa: VERSION 0.1.12 (problem presented itself in 0.1.10 too. Updated to see if 0.1.12 resolved issue)
RHEL 7.7
IPA: VERSION: 4.6.6, API_VERSION: 2.231 (ipa-common-4.6.6-11.el7.noarch, et al)
ANSIBLE:
ansible 2.9.6
config file = /etc/ansible/ansible.cfg
configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python2.7/site-packages/ansible
executable location = /usr/bin/ansible
python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

Playbook -v output:
`TASK [ipareplica : Install - DS enable SSL] ************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IndexError: list index out of range
fatal: [mediastore]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error

MODULE_STDERR:

Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_ipareplica_ds_enable_ssl_payload_0Ijdak/ansible_ipareplica_ds_enable_ssl_payload.zip/ansible/modules/ipareplica_ds_enable_ssl.py", line 207, in <module>
  File "/tmp/ansible_ipareplica_ds_enable_ssl_payload_0Ijdak/ansible_ipareplica_ds_enable_ssl_payload.zip/ansible/modules/ipareplica_ds_enable_ssl.py", line 199, in main
  File "/usr/lib/python2.7/site-packages/ipaserver/install/dsinstance.py", line 359, in enable_ssl
    self.start_creation()
  File "/usr/lib/python2.7/site-packages/ipaserver/install/service.py", line 567, in start_creation
    run_step(full_msg, method)
  File "/usr/lib/python2.7/site-packages/ipaserver/install/service.py", line 557, in run_step
    method()
  File "/usr/lib/python2.7/site-packages/ipaserver/install/dsinstance.py", line 815, in __enable_ssl
    dsdb.create_from_pkcs12(self.pkcs12_info[0], self.pkcs12_info[1],
IndexError: list index out of range
`

**Comment by t-woerner** [comment]
We should have a fix for this: 8ce5fd147aafc34e43dbe4246565c48eace2e115
A new ansible-freeipa release is planned to be released shortly and will provide this fix.

**Comment by rjeffman** [comment]
@jswindle-rtn, the fix was released in version 0.2.0. If you can, please, test if it is enough to solve your issue.

**Comment by jswindle-rtn** [comment]
Thanks for the notification.
I saw release earlier today and have already downloaded. Setting up to test now.
If it fixes my issues, then I'll update and close this issue.
If not, I'll update this issue with my findings.

**Comment by jswindle-rtn** [comment]
Release v0.2.0 solves this issue.
