### ISSUE TITLE
ERROR! couldn't resolve module/action 'freeipa.ansible_freeipa.iparole'.

### ISSUE THREAD

**Issue by toxynoid** [freeipa/ansible-freeipa#391]
I installed ansible_freeipa via ansible-galaxy. Version "0.1.12" as per MANIFEST.json.
I'm getting: ERROR! couldn't resolve module/action 'freeipa.ansible_freeipa.iparole'.
Other ansible_freeipa modules are working well.

**Comment by toxynoid** [comment]
Please create a new tag available in ansible-galaxy.

**Comment by rjeffman** [comment]
@toxynoid there should be a release, and a new tag on ansible-galaxy. soon, although I can't promise a date. Sorry for the delay.

**Comment by toxynoid** [comment]
Ok, thanks.
