### ISSUE TITLE
Is there any module for configuring automount?

### ISSUE THREAD

**Issue by dhilst** [freeipa/ansible-freeipa#401]
I'm consuming this playbook from another playbook and having things done by modules is much better than using shell module.

Is there any module to achieve this without resorting to shell?

```
  shell: |
    kinit admin <<< "{{ ipaadmin_password }}"
    ipa automountmap-add compute auto.spack
    ipa automountkey-add compute auto.master --key=/foo/bar --info=auto.foobar
    ipa automountkey-add compute auto.spack --key="*" --info="-fstype=nfs {{ fqdn }}:/foo/bar/&"
    ipa automountlocation-tofiles compute
 ```

Regards

**Comment by rjeffman** [comment]
I don't know of any existing module for automount. We plan to have one, but no date has been set so far.

If you want to contribute, we can help.

**Comment by dhilst** [comment]
I'm maintaining a playbook that make uses of various `ipa` commands through shell, I would like to replace most of them with ansible modules for sake of idempotece, but I'm little rushing now, besides ipa there are other softwares that are being set up with shell commands, my idea is, one day (it will be a great day), have everything with no shell commands to do this I will need to write some modules, I'm not very versed on module writing yet but it would be possible with some help. We can close this I get in touch when/if I write something :)

Regards

**Comment by drokath** [comment]
@rjeffman Fairly new to ansible but eager to learn. Which module should i use as a template ? I suppose ipalib will also have to be updated ?

**Comment by rjeffman** [comment]
@drokath there are many modules under de `plugins` directory. We also have a tool to create the module skeleton (`utils/new_module`).

You should familiarize yourself with the automount commands on IPA CLI, as we aim to support all attributes for the related commands (in this case `automountkey`, `automountlocation` and `automountmap`), and the FreeIPA python API, for which function and parameters can be found on [API.TXT](https://github.com/freeipa/freeipa/blob/master/API.txt) at the root of [FreeIPA's repository](https://github.com/freeipa/freeipa).

**Comment by chr15p** [comment]
I wrote some modules for this ages ago for a project that got cancelled, but I've dusted them off, rebased and raised [PR485](https://github.com/freeipa/ansible-freeipa/pull/485).  They're probably riddled with typos etc but hopefully are useful.

**Comment by rjeffman** [comment]
Automount configuration can now be achieved, as of version 1.6.1, with ipaautomountlocation, ipaautomountmap and ipaautomountkey management modules.

Thank you @chr15p for your contribution.

**Comment by dhilst** [comment]
Great work guys, thanks @chr15p
