### ISSUE TITLE
copy_external_cert does not handle pathed items

### ISSUE THREAD

**Issue by chsnell** [freeipa/ansible-freeipa#405]
The copy_external_cert.yml task file in the ipaserver role does not appear to handle pathed items, expecting just a file name, but without any validation.  If you provide a path, especially a relative path, Ansible then tries to follow that path relative to /root.  What happens if one were to put in a path like ../etc/passwd?

**Comment by chsnell** [comment]
To add to this, the name of the variable used (ipaserver_external_cert_files_from_controller) implies that multiple files can be handled, but the tasks file can only handle a single file.  Our site likes to keep our CA Chain in a separate file, with the chain for the service/application separate, which means 2 files.

**Comment by t-woerner** [comment]
`copy_external_cert` should only use the basename on the remote site.
