### ISSUE TITLE
ipauser module does not seem to support --check flag to ansible-playbook

### ISSUE THREAD

**Issue by chsnell** [freeipa/ansible-freeipa#407]
I ran a playbook that included adding some new accounts to IPA, but with the --check flag.  It appears that the accounts are now present on that system where they were not before, thus making me think --check isn't honored.  Maybe I missed that in the docs somewhere.

ansible-playbook 2.10.1
  config file = /home/itcxs02/dev/rci-ansible/ansible.cfg
  configured module search path = ['/home/itcxs02/.ansible/plugins/modules', '/home/itcxs02/dev/rci-ansible/library', '/usr/local/ansible/modules', '/usr/local/ansible/foreman-ansible-modules/plugins/modules', '/usr/lib/python2.7/site-packages/ansible/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

$ ansible-playbook -i environments/dev/ipa.txt playbooks/deploy-ipa.yml --check

[trimmed...]

TASK [ri_ipa_post : Ensure service accounts are present] ********************************************************
[WARNING]: Module did not set no_log for update_password
changed: [hostname.example.com]

PLAY RECAP ******************************************************************************************************
hostname.example.com : ok=5    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

Relevant section of role:
- name: Ensure service accounts are present
  ipauser:
    ipaadmin_password: "{{ ipaadmin_password }}"
    users: "{{ svc_users }}"

svc_users:
  - name: foobar
    first: foobar Production User
    last: .
    uid: 123456
    gid: 1
    shell: /bin/ksh
    homedir: /usr/local/foo
    noprivate: true

**Comment by rjeffman** [comment]
It is not only `ipauser`. I found, at least `iparole` module that is not respecting `--check` flag.

**Comment by varunmylaraiah** [comment]
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1893675

**Comment by enothen** [comment]
> 
> 
> Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1893675

Why a ticket to Red Hat? The bug is not RHEL8 as a product, but on the Ansible modules

**Comment by enothen** [comment]
Also, none of the modules on plugins/modules have the code to evaluate check_mode, so this is a general issue.

**Comment by rjeffman** [comment]
> Why a ticket to Red Hat? The bug is not RHEL8 as a product, but on the Ansible modules

Issue was cloned to RHEL 8 bugzilla since it is affected by it, and it allows prioritization for RHEL 8 developers to work on it. The more hands fixing issues here, the better.

Also, ansible-freeipa is not in Ansible's [Community General Collection](https://github.com/ansible-collections/community.general), and its issues are handled separately from the Ansible modules.

**Comment by rjeffman** [comment]
> Also, none of the modules on plugins/modules have the code to evaluate check_mode, so this is a general issue.

Yes, that's what I wrote above.

**Comment by rjeffman** [comment]
Fixed by #478
