### ISSUE TITLE
Cannot get subject base from server: invalid 'CA renewal master': all masters must have CA server role enabled

### ISSUE THREAD

**Issue by silanea** [freeipa/ansible-freeipa#41]
Fedora Server 28, latest commit plus my patches (https://github.com/silanea/ansible-freeipa/commit/1482f8de85c91cc1a2b82d76687b46ddcb825f08).

While debugging https://github.com/freeipa/ansible-freeipa/issues/39 I tried running install-server.yml with
`ipaserver_setup_adtrust: no`
and hit this:
```
TASK [ipaclient : Install - IPA API calls for remaining enrollment parts] *****************************************
fatal: [redacted]: FAILED! => {"changed": false, "msg": "Cannot get subject base from server: invalid 'CA renewal master': all masters must have CA server role enabled"}                                                           

TASK [ipaclient : Cleanup leftover ccache] ************************************************************************
changed: [redacted]
        to retry, use: --limit @/etc/ansible/ipa-servers.retry

PLAY RECAP ********************************************************************************************************
redacted                 : ok=30   changed=16   unreachable=0    failed=1
```
`ipaserver_setup_ca: yes` is set explicitly, though it should be the default anyway.

**Comment by t-woerner** [comment]
This has been fixed by: https://github.com/freeipa/ansible-freeipa/commit/dc0d1fc196db273edc01678931cd53c04cc87503

**Comment by t-woerner** [comment]
This has been fixed by: https://github.com/freeipa/ansible-freeipa/commit/dc0d1fc196db273edc01678931cd53c04cc87503
