### ISSUE TITLE
Adding AD user members to an external group?

### ISSUE THREAD

**Issue by chsnell** [freeipa/ansible-freeipa#418]
I'm trying to add users that come from a one-way AD trust into an existing external user group, but no matter what syntax I find, I always get an error that there is no such entry.  Here is a sample stanza:

- name: Ensure matching posix-ad groups are present
  ipagroup:
    ipaadmin_password: "{{ ipaadmin_password }}"
    action: member
    name: "group-ad"
    user: "username@ad.com"

Output of attempted run (sanitized):

TASK [ri_ipa_groups : Ensure matching posix-ad groups are present] **********************************************
task path: /home/aduser/dev/rci-ansible/roles/ri_ipa_groups/tasks/main.yml:19
<ipaserver> ESTABLISH SSH CONNECTION FOR USER: root
<ipaserver> SSH: EXEC sshpass -d11 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="./roles/automation-user/files/auto"' -o 'User="root"' -o ConnectTimeout=60 -o ControlPath=/home/aduser/.ansible/cp/04a2fc4369 ipaserver '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''
<ipaserver> (0, b'/root\n', b"Warning: Permanently added 'ipaserver' (ECDSA) to the list of known hosts.\r\n")
<ipaserver> ESTABLISH SSH CONNECTION FOR USER: root
<ipaserver> SSH: EXEC sshpass -d11 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="./roles/automation-user/files/auto"' -o 'User="root"' -o ConnectTimeout=60 -o ControlPath=/home/aduser/.ansible/cp/04a2fc4369 ipaserver '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1602259429.328126-231997-60317520310349 `" && echo ansible-tmp-1602259429.328126-231997-60317520310349="` echo /root/.ansible/tmp/ansible-tmp-1602259429.328126-231997-60317520310349 `" ) && sleep 0'"'"''
<ipaserver> (0, b'ansible-tmp-1602259429.328126-231997-60317520310349=/root/.ansible/tmp/ansible-tmp-1602259429.328126-231997-60317520310349\n', b'')
<ipaserver> Attempting python interpreter discovery
<ipaserver> ESTABLISH SSH CONNECTION FOR USER: root
<ipaserver> SSH: EXEC sshpass -d11 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="./roles/automation-user/files/auto"' -o 'User="root"' -o ConnectTimeout=60 -o ControlPath=/home/aduser/.ansible/cp/04a2fc4369 ipaserver '/bin/sh -c '"'"'echo PLATFORM; uname; echo FOUND; command -v '"'"'"'"'"'"'"'"'/usr/bin/python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.5'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/libexec/platform-python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/bin/python3'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python'"'"'"'"'"'"'"'"'; echo ENDFOUND && sleep 0'"'"''
<ipaserver> (0, b'PLATFORM\nLinux\nFOUND\n/usr/bin/python3.6\n/usr/libexec/platform-python\n/usr/bin/python3\nENDFOUND\n', b'')
<ipaserver> ESTABLISH SSH CONNECTION FOR USER: root
<ipaserver> SSH: EXEC sshpass -d11 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="./roles/automation-user/files/auto"' -o 'User="root"' -o ConnectTimeout=60 -o ControlPath=/home/aduser/.ansible/cp/04a2fc4369 ipaserver '/bin/sh -c '"'"'/usr/bin/python3.6 && sleep 0'"'"''
<ipaserver> (0, b'{"platform_dist_result": ["redhat", "8.2", "Ootpa"], "osrelease_content": "NAME=\\"Red Hat Enterprise Linux\\"\\nVERSION=\\"8.2 (Ootpa)\\"\\nID=\\"rhel\\"\\nID_LIKE=\\"fedora\\"\\nVERSION_ID=\\"8.2\\"\\nPLATFORM_ID=\\"platform:el8\\"\\nPRETTY_NAME=\\"Red Hat Enterprise Linux 8.2 (Ootpa)\\"\\nANSI_COLOR=\\"0;31\\"\\nCPE_NAME=\\"cpe:/o:redhat:enterprise_linux:8.2:GA\\"\\nHOME_URL=\\"https://www.redhat.com/\\"\\nBUG_REPORT_URL=\\"https://bugzilla.redhat.com/\\"\\n\\nREDHAT_BUGZILLA_PRODUCT=\\"Red Hat Enterprise Linux 8\\"\\nREDHAT_BUGZILLA_PRODUCT_VERSION=8.2\\nREDHAT_SUPPORT_PRODUCT=\\"Red Hat Enterprise Linux\\"\\nREDHAT_SUPPORT_PRODUCT_VERSION=\\"8.2\\"\\n"}\n', b'')
Using module file /usr/share/ansible/plugins/modules/ipagroup.py
<ipaserver> PUT /home/aduser/.ansible/tmp/ansible-local-231986pm58b52d/tmpwky17dwz TO /root/.ansible/tmp/ansible-tmp-1602259429.328126-231997-60317520310349/AnsiballZ_ipagroup.py
<ipaserver> SSH: EXEC sshpass -d11 sftp -o BatchMode=no -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="./roles/automation-user/files/auto"' -o 'User="root"' -o ConnectTimeout=60 -o ControlPath=/home/aduser/.ansible/cp/04a2fc4369 '[ipaserver]'
<ipaserver> (0, b'sftp> put /home/aduser/.ansible/tmp/ansible-local-231986pm58b52d/tmpwky17dwz /root/.ansible/tmp/ansible-tmp-1602259429.328126-231997-60317520310349/AnsiballZ_ipagroup.py\n', b'')
<ipaserver> ESTABLISH SSH CONNECTION FOR USER: root
<ipaserver> SSH: EXEC sshpass -d11 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="./roles/automation-user/files/auto"' -o 'User="root"' -o ConnectTimeout=60 -o ControlPath=/home/aduser/.ansible/cp/04a2fc4369 ipaserver '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1602259429.328126-231997-60317520310349/ /root/.ansible/tmp/ansible-tmp-1602259429.328126-231997-60317520310349/AnsiballZ_ipagroup.py && sleep 0'"'"''
<ipaserver> (0, b'', b'')
<ipaserver> ESTABLISH SSH CONNECTION FOR USER: root
<ipaserver> SSH: EXEC sshpass -d11 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="./roles/automation-user/files/auto"' -o 'User="root"' -o ConnectTimeout=60 -o ControlPath=/home/aduser/.ansible/cp/04a2fc4369 -tt ipaserver '/bin/sh -c '"'"'/usr/libexec/platform-python /root/.ansible/tmp/ansible-tmp-1602259429.328126-231997-60317520310349/AnsiballZ_ipagroup.py && sleep 0'"'"''
<ipaserver> (1, b'\r\n{"failed": true, "msg": "group_add_member: user AD\\\\aduser: no such entry", "invocation": {"module_args": {"ipaadmin_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "action": "member", "name": ["group-ad"], "user": ["AD\\\\aduser"], "ipaadmin_principal": "admin", "state": "present", "description": null, "gid": null, "nonposix": null, "external": null, "nomembers": null, "group": null, "service": null}}}\r\n', b'Shared connection to ipaserver closed.\r\n')
<ipaserver> Failed to connect to the host via ssh: Shared connection to ipaserver closed.
<ipaserver> ESTABLISH SSH CONNECTION FOR USER: root
<ipaserver> SSH: EXEC sshpass -d11 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="./roles/automation-user/files/auto"' -o 'User="root"' -o ConnectTimeout=60 -o ControlPath=/home/aduser/.ansible/cp/04a2fc4369 ipaserver '/bin/sh -c '"'"'rm -f -r /root/.ansible/tmp/ansible-tmp-1602259429.328126-231997-60317520310349/ > /dev/null 2>&1 && sleep 0'"'"''
<ipaserver> (0, b'', b'')
fatal: [ipaserver]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "action": "member",
            "description": null,
            "external": null,
            "gid": null,
            "group": null,
            "ipaadmin_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "ipaadmin_principal": "admin",
            "name": [
                "group-ad"
            ],
            "nomembers": null,
            "nonposix": null,
            "service": null,
            "state": "present",
            "user": [
                "AD\\aduser"
            ]
        }
    }
}

MSG:

group_add_member: user AD\aduser: no such entry

I've tried every permutation I can think of for that user name:
AD\user
user@ad.com
user@ad
an actual SID (S-1-5...)

If someone has gotten this working, can they please share the correct format.  You can add it through the ipa cli with ipa group-add-member group-ad --external 'AD\user' as long as you leave the rest of the prompts empty.

**Comment by RobVerduijn** [comment]
Hi,
You can't add ad users to ipa groups
You can only add ad-groups to ipa groups
You can read the instructions here [redhat doc ](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html-single/windows_integration_guide/index#trust-groups)

and when you use ansible to do this you will hit this issue #160 

Rob

**Comment by chsnell** [comment]
> You can't add ad users to ipa groups
> You can only add ad-groups to ipa groups
> You can read the instructions here [redhat doc ](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html-single/windows_integration_guide/index#trust-groups)

From those docs:
"Both AD users and AD groups can be added directly to IdM user groups."  Both the IPA web UI and the IPA cli allow this operation.  The ipagroup module does allow me to create the group as external (although, that operation isn't idempotent), and allows me to add the group into a posix group as a group_member.  It just doesn't allow me to add non-IPA users to the group.

**Comment by chsnell** [comment]
For additional information, this is a RHEL 8 IDM server:
[root@vrh8idmpchqd01 ~]# ipa --version
VERSION: 4.8.4, API_VERSION: 2.235
[root@vrh8idmpchqd01 ~]# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.2 (Ootpa)

**Comment by chsnell** [comment]
$ ansible --version
ansible 2.10.1
  config file = /home/user/dev/rci-ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/home/user/dev/rci-ansible/library', '/usr/local/ansible/modules', '/usr/local/ansible/foreman-ansible-modules/plugins/modules', '/usr/lib/python2.7/site-packages/ansible/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

**Comment by abbra** [comment]
You need to specify --external when adding an external group member. That's in CLI.  In your json debug output the external field is empty and the member is instead in 'user' field. That's your mistake here.
Both groups and users can be added as external members. All what's required is that they are resolvable to SIDs through sssd.

**Comment by chsnell** [comment]
The external option is a boolean.  If I set it to true on a pre-existing group, I get a message like this:
group_mod: test-ad: This group already allows external members

Having the external flag set to true while having an AD user in the user field produces the same error.  You also cannot have action: member set while external is set.  The only field I can see to put actual user names is that user field.

There are no samples in the README for ipagroup that show the proper use of external and adding members.

TASK [ri_ipa_groups : Ensure matching posix-ad groups are present] **********************************************
task path: /home/itcxs02/dev/rci-ansible/roles/ri_ipa_groups/tasks/main.yml:19
<vrh8idmpchqd01> ESTABLISH SSH CONNECTION FOR USER: root
<vrh8idmpchqd01> SSH: EXEC sshpass -d11 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="./roles/automation-user/files/auto"' -o 'User="root"' -o ConnectTimeout=60 -o ControlPath=/home/itcxs02/.ansible/cp/04a2fc4369 vrh8idmpchqd01 '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''
<vrh8idmpchqd01> (0, b'/root\n', b'')
<vrh8idmpchqd01> ESTABLISH SSH CONNECTION FOR USER: root
<vrh8idmpchqd01> SSH: EXEC sshpass -d11 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="./roles/automation-user/files/auto"' -o 'User="root"' -o ConnectTimeout=60 -o ControlPath=/home/itcxs02/.ansible/cp/04a2fc4369 vrh8idmpchqd01 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1602285394.966875-235407-174125077685896 `" && echo ansible-tmp-1602285394.966875-235407-174125077685896="` echo /root/.ansible/tmp/ansible-tmp-1602285394.966875-235407-174125077685896 `" ) && sleep 0'"'"''
<vrh8idmpchqd01> (0, b'ansible-tmp-1602285394.966875-235407-174125077685896=/root/.ansible/tmp/ansible-tmp-1602285394.966875-235407-174125077685896\n', b'')
<vrh8idmpchqd01> Attempting python interpreter discovery
<vrh8idmpchqd01> ESTABLISH SSH CONNECTION FOR USER: root
<vrh8idmpchqd01> SSH: EXEC sshpass -d11 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="./roles/automation-user/files/auto"' -o 'User="root"' -o ConnectTimeout=60 -o ControlPath=/home/itcxs02/.ansible/cp/04a2fc4369 vrh8idmpchqd01 '/bin/sh -c '"'"'echo PLATFORM; uname; echo FOUND; command -v '"'"'"'"'"'"'"'"'/usr/bin/python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.5'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/libexec/platform-python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/bin/python3'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python'"'"'"'"'"'"'"'"'; echo ENDFOUND && sleep 0'"'"''
<vrh8idmpchqd01> (0, b'PLATFORM\nLinux\nFOUND\n/usr/bin/python3.6\n/usr/libexec/platform-python\n/usr/bin/python3\nENDFOUND\n', b'')
<vrh8idmpchqd01> ESTABLISH SSH CONNECTION FOR USER: root
<vrh8idmpchqd01> SSH: EXEC sshpass -d11 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="./roles/automation-user/files/auto"' -o 'User="root"' -o ConnectTimeout=60 -o ControlPath=/home/itcxs02/.ansible/cp/04a2fc4369 vrh8idmpchqd01 '/bin/sh -c '"'"'/usr/bin/python3.6 && sleep 0'"'"''
<vrh8idmpchqd01> (0, b'{"platform_dist_result": ["redhat", "8.2", "Ootpa"], "osrelease_content": "NAME=\\"Red Hat Enterprise Linux\\"\\nVERSION=\\"8.2 (Ootpa)\\"\\nID=\\"rhel\\"\\nID_LIKE=\\"fedora\\"\\nVERSION_ID=\\"8.2\\"\\nPLATFORM_ID=\\"platform:el8\\"\\nPRETTY_NAME=\\"Red Hat Enterprise Linux 8.2 (Ootpa)\\"\\nANSI_COLOR=\\"0;31\\"\\nCPE_NAME=\\"cpe:/o:redhat:enterprise_linux:8.2:GA\\"\\nHOME_URL=\\"https://www.redhat.com/\\"\\nBUG_REPORT_URL=\\"https://bugzilla.redhat.com/\\"\\n\\nREDHAT_BUGZILLA_PRODUCT=\\"Red Hat Enterprise Linux 8\\"\\nREDHAT_BUGZILLA_PRODUCT_VERSION=8.2\\nREDHAT_SUPPORT_PRODUCT=\\"Red Hat Enterprise Linux\\"\\nREDHAT_SUPPORT_PRODUCT_VERSION=\\"8.2\\"\\n"}\n', b'')
Using module file /usr/share/ansible/plugins/modules/ipagroup.py
<vrh8idmpchqd01> PUT /home/itcxs02/.ansible/tmp/ansible-local-235396irs2v0hx/tmpe0_zkv8o TO /root/.ansible/tmp/ansible-tmp-1602285394.966875-235407-174125077685896/AnsiballZ_ipagroup.py
<vrh8idmpchqd01> SSH: EXEC sshpass -d11 sftp -o BatchMode=no -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="./roles/automation-user/files/auto"' -o 'User="root"' -o ConnectTimeout=60 -o ControlPath=/home/itcxs02/.ansible/cp/04a2fc4369 '[vrh8idmpchqd01]'
<vrh8idmpchqd01> (0, b'sftp> put /home/itcxs02/.ansible/tmp/ansible-local-235396irs2v0hx/tmpe0_zkv8o /root/.ansible/tmp/ansible-tmp-1602285394.966875-235407-174125077685896/AnsiballZ_ipagroup.py\n', b'')
<vrh8idmpchqd01> ESTABLISH SSH CONNECTION FOR USER: root
<vrh8idmpchqd01> SSH: EXEC sshpass -d11 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="./roles/automation-user/files/auto"' -o 'User="root"' -o ConnectTimeout=60 -o ControlPath=/home/itcxs02/.ansible/cp/04a2fc4369 vrh8idmpchqd01 '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1602285394.966875-235407-174125077685896/ /root/.ansible/tmp/ansible-tmp-1602285394.966875-235407-174125077685896/AnsiballZ_ipagroup.py && sleep 0'"'"''
<vrh8idmpchqd01> (0, b'', b'')
<vrh8idmpchqd01> ESTABLISH SSH CONNECTION FOR USER: root
<vrh8idmpchqd01> SSH: EXEC sshpass -d11 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="./roles/automation-user/files/auto"' -o 'User="root"' -o ConnectTimeout=60 -o ControlPath=/home/itcxs02/.ansible/cp/04a2fc4369 -tt vrh8idmpchqd01 '/bin/sh -c '"'"'/usr/libexec/platform-python /root/.ansible/tmp/ansible-tmp-1602285394.966875-235407-174125077685896/AnsiballZ_ipagroup.py && sleep 0'"'"''
<vrh8idmpchqd01> (1, b'\r\n{"failed": true, "msg": "group_add_member: user RAILINC\\\\itcxs02: no such entry", "invocation": {"module_args": {"ipaadmin_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "external": true, "name": ["test-ad"], "user": ["RAILINC\\\\itcxs02"], "ipaadmin_principal": "admin", "action": "group", "state": "present", "description": null, "gid": null, "nonposix": null, "nomembers": null, "group": null, "service": null}}}\r\n', b'Shared connection to vrh8idmpchqd01 closed.\r\n')
<vrh8idmpchqd01> Failed to connect to the host via ssh: Shared connection to vrh8idmpchqd01 closed.
<vrh8idmpchqd01> ESTABLISH SSH CONNECTION FOR USER: root
<vrh8idmpchqd01> SSH: EXEC sshpass -d11 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="./roles/automation-user/files/auto"' -o 'User="root"' -o ConnectTimeout=60 -o ControlPath=/home/itcxs02/.ansible/cp/04a2fc4369 vrh8idmpchqd01 '/bin/sh -c '"'"'rm -f -r /root/.ansible/tmp/ansible-tmp-1602285394.966875-235407-174125077685896/ > /dev/null 2>&1 && sleep 0'"'"''
<vrh8idmpchqd01> (0, b'', b'')
fatal: [vrh8idmpchqd01]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "action": "group",
            "description": null,
            "external": true,
            "gid": null,
            "group": null,
            "ipaadmin_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "ipaadmin_principal": "admin",
            "name": [
                "test-ad"
            ],
            "nomembers": null,
            "nonposix": null,
            "service": null,
            "state": "present",
            "user": [
                "AD\\aduser"
            ]
        }
    }
}

MSG:

group_add_member: user AD\aduser: no such entry

**Comment by abbra** [comment]
This looks like a bug in the ansible module code. `ipa group-add-member --external` is a String, not a Flag.

**Comment by chsnell** [comment]
Dug into the code a little.  In the ipagroup.py module, it looks like gen_member_args (line 206) needs to accept the external flag and then set the correct argument to add the user to if it is an external group.

**Comment by rjeffman** [comment]
@chsnell, I tried to create a fix for this issue, but it was like "flying with instruments", as I'm not able to test it, since I don't have a trust setup.

Could you please test the ipagroup plugin available in PR #420?

**Comment by RobVerduijn** [comment]
Works for me as well.

Nice one.

**Comment by chsnell** [comment]
This PR was merged, and it seems to be working ok, so this can be closed.

**Comment by rjeffman** [comment]
Thank you for testing, @chsnell
