### ISSUE TITLE
[Permission Handling] Not able to add member privilege while adding permission

### ISSUE THREAD

**Issue by varunmylaraiah** [freeipa/ansible-freeipa#425]
Not able to add member privilege while adding permission. But able to add member privilege on existing permission.

**New Permission:**
[root@ansible ~]# cat perm16a.yaml
- name: Playbook to
  hosts: ipaserver

  tasks:
  - ipapermission:
      ipaadmin_password: <XXXXPasswordXXXX>
      name: 02MyPermission
      object_type: user
      right: read
      privilege: "User Administrators"

[root@ansible ~]# ansible-playbook -vv -i inventory/server.hosts perm16a.yaml
ansible-playbook 2.9.11
  config file = /root/ansible.cfg
  configured module search path = ['/root/ansible-freeipa/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.5 (default, Aug 12 2020, 00:00:00) [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]
Using /root/ansible.cfg as config file

PLAYBOOK: perm16a.yaml ***********************************************************************************************
1 plays in perm16a.yaml

PLAY [Playbook to] ***************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************
task path: /root/perm16a.yaml:2
[DEPRECATION WARNING]: Distribution fedora 32 on host master.ipadomain.test should use /usr/bin/python3, but is using
 /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to 
using the discovered platform python for this host. See 
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information. This 
feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False 
in ansible.cfg.
ok: [master.ipadomain.test]
META: ran handlers

TASK [ipapermission] *************************************************************************************************
task path: /root/perm16a.yaml:6
fatal: [master.ipadomain.test]: FAILED! => {"changed": false, "msg": "argument of type 'NoneType' is not iterable"}

PLAY RECAP ***********************************************************************************************************
master.ipadomain.test      : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

**Existing Permission:**
```
[root@master ~]# ipa permission-show 01MyPermission
  Permission name: 01MyPermission
  Granted rights: read
  Effective attributes: audio, cn
  Bind rule type: permission
  Subtree: cn=users,cn=accounts,dc=ipadomain,dc=test
  Type: user
  Permission flags: SYSTEM, V2
  Granted to Privilege: Host Group Administrators
  Indirect Member of roles: IT Specialist
```

```
[root@ansible ~]# cat test16.yaml
- name: Playbook to
  hosts: ipaserver

  tasks:
  - ipapermission:
      ipaadmin_password: <XXXXPasswordXXXX>
      name: 01MyPermission
      privilege: "Host Administrators"

[root@ansible ~]# ansible-playbook -vv -i inventory/server.hosts test16.yaml
ansible-playbook 2.9.11
  config file = /root/ansible.cfg
  configured module search path = ['/root/ansible-freeipa/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.5 (default, Aug 12 2020, 00:00:00) [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]
Using /root/ansible.cfg as config file

PLAYBOOK: test16.yaml ************************************************************************************************
1 plays in test16.yaml

PLAY [Playbook to] ***************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************
task path: /root/test16.yaml:2
[DEPRECATION WARNING]: Distribution fedora 32 on host master.ipadomain.test should use /usr/bin/python3, but is using
 /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to 
using the discovered platform python for this host. See 
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information. This 
feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False 
in ansible.cfg.
ok: [master.ipadomain.test]
META: ran handlers

TASK [ipapermission] *************************************************************************************************
task path: /root/test16.yaml:6
changed: [master.ipadomain.test] => {"changed": true}
META: ran handlers
META: ran handlers

PLAY RECAP ***********************************************************************************************************
master.ipadomain.test      : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```
```
[root@master ~]# ipa permission-show 01MyPermission
  Permission name: 01MyPermission
  Granted rights: read
  Effective attributes: audio, cn
  Bind rule type: permission
  Subtree: cn=users,cn=accounts,dc=ipadomain,dc=test
  Type: user
  Permission flags: SYSTEM, V2
  Granted to Privilege: Host Administrators
  Indirect Member of roles: IT Specialist
```

**Comment by varunmylaraiah** [comment]
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1893688

**Comment by t-woerner** [comment]
The permission module may not handle prvileges. An IPA internal only API has been moved for this. The privilege variable and all related code paths will be removed.
