### ISSUE TITLE
please release a new version of the ansible collection

### ISSUE THREAD

**Issue by RobVerduijn** [freeipa/ansible-freeipa#447]
Hello,

The current collection (0.2.1) of ansible freeipa from ansible galaxy fails to install ipa-server for me,
However the github version of today (20201119-10:47)  works fine.

Please release a new version of the collection on ansible galaxy.

Rob

**Comment by chsnell** [comment]
Could you explain a little more about the problems with the current version?  What variable setup?  What version of ansible?  What base OS?  I ask as I was able to use the 0.2.0 & 0.2.1 versions without issue at my $WORK site.

**Comment by RobVerduijn** [comment]
Since the github version was working I did not bother to deep dive into the collection to see what was wrong.

This was a new lab setup using centos8 with all updates, ansible 2.9.15.
One modification was done in both cases (with the collection and github), I used clean installs for all tests,  a new vm was created for each case.
One workaround was applied.
To get it to work the workaround of downgrading the openjdk version was required due to this [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1892216)

The downgrade was applied before using the collection and for the github version.
I added a workaround to my play to enable the idm module and install the ipaserver packages, download the previous openjdk packages (sadly centos doesn't keep them in the repo like rhel does) and downgraded the openjdk-packages. 

Rob

**Comment by RobVerduijn** [comment]
now I think about it, simply downloading and installing the older openjdk packages would have been sufficient as a workaround.
ah well, as soon as centos updates to 8.3 it probably isn't needed anymore since that bug is already fixed in rhel.

Rob

**Comment by rjeffman** [comment]
The openjdk issue is a CentOS packaging problem, and, unfortunately, there is nothing we can do about it.

**Comment by RobVerduijn** [comment]
I know it is a CentOS package issue.

Even including the workaround the collection failed, and the github version works.
Hence my request to do a new release.

Rob

**Comment by t-woerner** [comment]
ansible-freeipa 0.3.0 has been released and is now available on galaxy.

If there is any issue, let us know. If you like the ansible-freeipa collection on galaxy, please rate it.
