### ISSUE TITLE
ipa: ERROR: invalid 'CA renewal master': all masters must have CA server role enabled

### ISSUE THREAD

**Issue by dongursli** [freeipa/ansible-freeipa#45]
IPA CA is not created by default when setting up server

Inventory used 
[ipaserver]
ipaserver2.example.com

[ipaserver:vars]
ipaserver_domain=example.com
ipaserver_realm=EXAMPLE.COM
ipaadmin_password=....
ipadm_password=...

`]# ipa config-show`
`ipa: ERROR: invalid 'CA renewal master': all masters must have CA server role enabled`

**Comment by nkinder** [comment]
I also see this error trying to create a new single IPA server.  I see the failure when running the playbook after it finishes the server portion of the install:

  TASK [ipaclient : Install - IPA API calls for remaining enrollment parts] **************************

It then fails with this:

`WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_ipaapi_payload_MV1r2I/__main__.py", line 198, in main
    config = api.Command['config_show']()['result']
  File "/usr/lib/python2.7/site-packages/ipalib/frontend.py", line 447, in __call__
    return self.__do_call(*args, **options)
  File "/usr/lib/python2.7/site-packages/ipalib/frontend.py", line 475, in __do_call
    ret = self.run(*args, **options)
  File "/usr/lib/python2.7/site-packages/ipalib/frontend.py", line 798, in run
    return self.forward(*args, **options)
  File "/usr/lib/python2.7/site-packages/ipalib/frontend.py", line 821, in forward
    *args, **kw)
  File "/usr/lib/python2.7/site-packages/ipalib/rpc.py", line 1109, in forward
    return self._call_command(command, params)
  File "/usr/lib/python2.7/site-packages/ipalib/rpc.py", line 1085, in _call_command
    return command(*params)
  File "/usr/lib/python2.7/site-packages/ipalib/rpc.py", line 1239, in _call
    return self.__request(name, args)
  File "/usr/lib/python2.7/site-packages/ipalib/rpc.py", line 1233, in __request
    raise error_class(**kw)

fatal: [ipa.example.ngk]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "debug": false,
            "hostname": "ipa.example.ngk",
            "realm": "EXAMPLE.NGK",
            "servers": [
                "ipa.example.ngk"
            ]
        }
    },
    "msg": "Cannot get subject base from server: invalid 'CA renewal master': all masters must have CA server role enabled"
}`

**Comment by balux** [comment]
I can confirm this on CentOS 7. Does a workaround exist?

**Comment by kirikae** [comment]
I can confirm this is an issue with both Fedora 29 and CentOS 7 (both fully up-to-date) when attempting to run this role to install a single FreeIPA server onto either of them.

Both fresh installs.

I have also attempt what was a potential fix by applying the patch from @selanea, who appears to have logged an identical Issue, #41.

From my limited understanding and knowledge of Python, the issues appears to be from the `roles/ipaclient/library/ipaapi.py`, with line 200 of the code being the part that spits the error in question.

Noting what the error says I can only assume that this is to do with configuring FreeIPA with a CA going wrong, or having changed in a recent FreeIPA update?

**Comment by fmontaldo** [comment]
HI folks:

I got a similar issue when I run the playbook.

TASK [ipaclient : Install - IPA API calls for remaining enrollment parts] ****************************************************************************************************************************************************************************************************
task path: /var/lib/awx/projects/ansible-freeipa/roles/ipaclient/tasks/install.yml:224
fatal: [ipaserver.lab.com]: FAILED! => {"changed": false, "msg": "Cannot get subject base from server: invalid 'CA renewal master': all masters must have CA server role enabled"}

I changed the pythn script as per this link:

https://github.com/silanea/ansible-freeipa/commit/1482f8de85c91cc1a2b82d76687b46ddcb825f08#diff-94f067738dd129d2a9a6af67d9bf3349

What is the error?

**Comment by t-woerner** [comment]
This has been fixed by: https://github.com/freeipa/ansible-freeipa/commit/dc0d1fc196db273edc01678931cd53c04cc87503
