### ISSUE TITLE
ipareplica_no_dnssec_validation

### ISSUE THREAD

**Issue by 2342435** [freeipa/ansible-freeipa#456]
Hi,
here:
https://github.com/freeipa/ansible-freeipa/blob/master/roles/ipareplica/library/ipareplica_setup_dns.py
Line 145,146:
options.no_dnssec_validation = ansible_module.params.get(
        'no_dnssec_validationdnssec_validation')

(double paste)
Sry, no developer, don't know how to push.

Even if i fix the typo, ipareplica_no_dnssec_validation isn't used - so dnssec seems to be alway active for forwarders in replica-setup - when replica_setup_dns: yes.
I'll try to find out why, but it's all magic ;-)

(dnssec isn't possible in current env here)
Thanks for your work.

**Comment by rjeffman** [comment]
Thank you for the report. A fix has been merged, and this issue will be then closed.

If your problem persist, please let us know.
