### ISSUE TITLE
Variables for external CA

### ISSUE THREAD

**Issue by dongursli** [freeipa/ansible-freeipa#46]
Please add configuration / variables for using external CA
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/linux_domain_identity_authentication_and_policy_guide/install-server#install-server-external-ca

**Comment by t-woerner** [comment]
I have been working on the support of external CA already. But with the code to handle external CA in FreeIPA this is not a simple tasks and is easily breaking the deployment of a cluster with several nodes (server, replica and clients). There is a plan to support for external CA without a two step process in the installer.

**Comment by t-woerner** [comment]
The external CA support has been completed with version 0.1.10.
