### ISSUE TITLE
ansible_freeipa_module.py uses socket.inet_pton(socket.AF_INET, ipAddress) which can not validate ip network addresses

### ISSUE THREAD

**Issue by toxynoid** [freeipa/ansible-freeipa#475]
If I put a network address i.e.192.168.99.0/24 in `allow_transfer` it does not get validated by `is_ipv4_addr(ipaddr)` because `socket.inet_pton(socket.AF_INET, ipAddress)` will always fail for network addresses.
Do I miss anything?

**Comment by rjeffman** [comment]
I believe you are talking about the `ipadnszone` module.

The module should accept IP addresses, network adresses, `none` or `any`, but currently it only accepts IPv4 or IPv6 addresses.

I'm marking this issue as a `bug`. Thank you for the report.

**Comment by rjeffman** [comment]
Closing as the fix was merged.
