### ISSUE TITLE
Max_Concurrent not valid task attr

### ISSUE THREAD

**Issue by edcrosbys** [freeipa/ansible-freeipa#48]
Attempting to install cluster. Get error:
ERROR! 'max_concurrent' is not a valid attribute for a Task

The error appears to have been in './ansible-freeipa/roles/ipareplica/tasks/install.yml': line 406, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

Commenting out max_concurrent (line 429) resolves the problem. I'm running ansible 2.7.1. I also only have 1 replica!

**Comment by cjeanner** [comment]
Same issue. I didn't find an equivalent of that one for newer ansible :(.

**Comment by cjeanner** [comment]
According to this *open* pull-request against ansible, I'd say ansible-freeipa is using a custom ansible code ??
https://github.com/ansible/ansible/pull/42528

**Comment by t-woerner** [comment]
ansible 2.7.1 seems to be the first version complaining on unknown task attributes. I added the attribute to do the tests and simply left it there as ansible was ignoring it. I will remove the attribute again.

**Comment by t-woerner** [comment]
This is the commit that added the max_concurrent attribute: https://github.com/freeipa/ansible-freeipa/commit/7a76f73bc4f2e8edff3ff80bf348081d7272b09c
