### ISSUE TITLE
ipareplica role ignores "ipaclient_no_ntp"

### ISSUE THREAD

**Issue by jake2184** [freeipa/ansible-freeipa#480]
I have `ipaclient_no_ntp: False` , but the ipareplica role doesn't use this in the task "Install - Setup Client". It uses the following logic:
```
      ipaclient_no_ntp: "{{ result_ipareplica_test.ipa_python_version
                            < 40690 }}"
```
Causing the client role to edit NTP config.

Is there a reason for this?

**Comment by rjeffman** [comment]
This is a duplicate of #479.
