### ISSUE TITLE
[Permission handling] Not able to rename permission

### ISSUE THREAD

**Issue by varunmylaraiah** [freeipa/ansible-freeipa#488]
Not able to rename permission name using rename variable

Error: fatal: [master.ipadomain.test]: FAILED! => {"changed": false, "msg": "Argument 'rename' can not be used with action 'permission' and state 'present'"}

@t-woerner This was working fine before merging https://github.com/freeipa/ansible-freeipa/pull/484. This is regression issue

```
Console Output:
[root@master ~]# ipa permission-show testPermission
  Permission name: testPermission
  Granted rights: read
  Effective attributes: audio
  Bind rule type: permission
  Subtree: cn=users,cn=accounts,dc=ipadomain,dc=test
  Type: user
  Permission flags: SYSTEM, V2


[root@master ~]# ipa permission-show newtestPermission
ipa: ERROR: newtestPermission: permission not found

[root@ansible ~]# cat renamed.yaml
---
- name: Playbook to ensure permission is renamed
  hosts: ipaserver

  tasks:
  - ipapermission:
      ipaadmin_password: <xxxxxxxxxxx>
      name: testPermission
      rename: newtestPermission
```

**Comment by t-woerner** [comment]
Your task is missing `state: renamed`.

**Comment by t-woerner** [comment]
There was a but that allowed to use `rename` also with `state:present`. This has been fixed and therefore `rename` is only working with `state: renamed` now as documented.
