### ISSUE TITLE
[RFE] Add Support for Certificate APIs

### ISSUE THREAD

**Issue by kresss** [freeipa/ansible-freeipa#494]
Can we add support for requesting and maintaining certificates.

Ideally a user could follow the workflows of the `ipa-getcert` command; however, that command seems to go beyond the functionality of the IPA API. At a minimum, I think functionality should be worked in to a new module to cover the following API end points:

- cert_find
- cert_remove_hold
- cert_request
- cert_revoke
- cert_show
- cert_status

**Comment by rjeffman** [comment]
@kresss currently the focus on certificate management is on using the [certificate Linux System Role](https://github.com/linux-system-roles/certificate), which currently allows to issue and renew certificates using IPA.

**Comment by kresss** [comment]
@rjeffman Sounds good. I took a quick look at the examples and it looks pretty good. I think it covers the cert_request functionality, but falls short on the functionality provided by the other API end points. That said, my guess is that it covers >80% of normal use cases.

**Comment by rjeffman** [comment]
@kresss the certificate role still lacks some desired functionality, but I believe it will have better support for certificates earlier that ansible-freeipa (which will support cert-* commands, but I can't say when).

**Comment by bouchardh** [comment]
@rjeffman I would like to add my vote to this enhancement.  Sometimes, it's nice to have the certificate and key in memory and plug it in the application you are deploying without writing it to too many disks.

**Comment by rjeffman** [comment]
A management module for `ipacert` has been added to the collection to manage certificates with PR #687. Some functionality on querying certificates with be added in the future when a module to retrieve object information is implemented.
