### ISSUE TITLE
DNS breaks on all client nodes when playbook is run

### ISSUE THREAD

**Issue by ElTimablo** [freeipa/ansible-freeipa#506]
I'm trying to enroll 5 Ubuntu machines against a Fedora 33 FreeIPA server.

DNS on all client machines (provided by the FreeIPA server) works fine until I run the playbook, at which point it breaks and I have to run ``netplan apply`` in order to resolve DNS again.
Please let me know which logs are relevant and I will provide them.

**Comment by rjeffman** [comment]
Which version of ansible-freeipa are you using? Which version of Ansible?

Can you provide the playbook you mentioned? Or, at least, a minimum playbook, or a way to reproduce the error?

**Comment by ElTimablo** [comment]
I'm hitting the error when running playbooks/install-client.yml with the following:
``ansible-playbook -i /etc/ansible/hosts -bkK playbooks/install-client.yml``

I'm using Ansible version 2.9.6 from the Ubuntu 20.04 repositories. I'm unsure where to check for the version of ansible-freeipa, though.

**Comment by rjeffman** [comment]
Can you provide the output of `ansible-playbook -i /etc/ansible/hosts -vvv -bkK playbooks/install-client.yml`?

**Comment by ElTimablo** [comment]
Should I uninstall the clients first?

**Comment by rjeffman** [comment]
If it is the install-client playbook that is failing, you don't need to. If not, I didn't get what the error is.

**Comment by ElTimablo** [comment]
Sorry for the silence. I've been trying to gather more information to determine if this is actually where I should be filing the bug. My hunch is that it's something to do with netplan rather than Ansible, but either way I've been unable to reproduce the issue lately. I'm going to keep trying to reproduce it (since I'm going to be enrolling more machines soon anyway), but for now I think it's probably safe to chalk this one up as not an issue. Sorry for the trouble.
