### ISSUE TITLE
 ipa-client installation with OTP is failed with error code 7(keytab: /usr/sbin/ipa-rmkeytab returned 7)

### ISSUE THREAD

**Issue by varunmylaraiah** [freeipa/ansible-freeipa#510]
Cloned : https://bugzilla.redhat.com/show_bug.cgi?id=1931381

Description of problem:
 ipa-client installation with OTP is failed with error code 7(keytab: /usr/sbin/ipa-rmkeytab returned 7)

Version-Release number of selected component (if applicable):
ipa-client-4.9.2-1
ipa-server-4.9.2-1

How reproducible:
100%

Steps to Reproduce:
I install the client with OTP

Actual results:
TASK [ipaclient : Install - Purge IPADOMAIN.TEST from host keytab] ***************************************************************************************************************************************************************************
task path: /usr/share/ansible/roles/ipaclient/tasks/install.yml:175
fatal: [client1.ipadomain.test]: FAILED! => {"changed": true, "cmd": ["/usr/sbin/ipa-rmkeytab", "-k", "/etc/krb5.keytab", "-r", "IPADOMAIN.TEST"], "delta": "0:00:00.006114", "end": "2021-02-19 07:59:25.697401", "failed_when_result": true, "msg": "non-zero return code", "rc": 7, "start": "2021-02-19 07:59:25.691287", "stderr": "Failed to set cursor 'No such file or directory'", "stderr_lines": ["Failed to set cursor 'No such file or directory'"], "stdout": "", "stdout_lines": []}

Expected results:
Should ignore error code 7

**Comment by Tcharl** [comment]
Hi power committers

I see that you tag frequently some times: can a new tag being created after this merge? I tried all combination on a fresh fedora 33 and they are all ending by an error code 7...
