### ISSUE TITLE
repeatable ipahost absent plays

### ISSUE THREAD

**Issue by 2342435** [freeipa/ansible-freeipa#516]
Hi,

absent-plays with ipahost fail, when host is not existing.
(
fatal: [ipa01]: FAILED! => {"changed": false, "msg": "host_show failed: supertesthost: host not found"}
)

I'd expect, that i can repeat absent-plays, too. (play should end with ok, when host_show failed)

Regards

Sören

**Comment by rjeffman** [comment]
Are you trying to ensure the host is absent or a member of a host is absent?
Which ansible-freeipa version are you using?
Can you share your playbook?

**Comment by 2342435** [comment]
Hi,

`
- name: remove host
  hosts: ipaserver
  tasks:
  - ipahost:
      ipaadmin_password: "{{ vault_ipa_admin_password }}"
      name: mynonexistentone
      state: absent
    run_once: true
`
fatal: [ipam]: FAILED! => {"changed": false, "msg": "host_show failed: mynonexistentone: host nicht gefunden"} 

The playbook is to make sure an host is absent. - When sb just removed it or it has a hardware failure and no clean uninstall is possible.
From my understanding it should be "OK", when there is no host with that name. 

Version: MANIFEST says 0.3.5.

Thx and regards

Sören

**Comment by rjeffman** [comment]
Now I could reproduce your issue.

As a workaround (until it is fixed), please, set the locale in your controler to "C", as in:
```
LC_ALL="C" ansible-playbook -i inventory playbook.yml
```

**Comment by 2342435** [comment]
Thank you very much!
