### ISSUE TITLE
What are the requirements to run the modules in a host without IDM? 

### ISSUE THREAD

**Issue by itcultus** [freeipa/ansible-freeipa#525]
So far I manage my IDM servers from the IDM servers themselves. 
However, when I create a service for example, I would like to do it from the target host and not to use delegate_to. 
I am sure that you mention it somewhere, but I cannot find it. 
So, a more clear (or if it doesn't exists!) "Requirements" section in the Readme is needed. 

As an example, I try to create a service on one of my HTTP servers, which requires a dummy host. 
What I get if I run the `ipahost` module without `delegate_to: <ipa_server>` is this: 

```
msg: No module named ipaserver.plugins
```

So, what is needed?

**Comment by rjeffman** [comment]
All `ansible-freeipa` modules are executed on the IPA server. The controller can be any machine with Ansible.
I control the server by adding `hosts: ipaserver` to the playbook and defining `ipaserver` in my inventory file.

See the examples on the [`ipahost` module README](https://github.com/freeipa/ansible-freeipa/blob/master/README-host.md).

**Comment by rjeffman** [comment]
PR #631 allows ansible-freeipa plugins to be executed on IdM clients.

I'm closing this issue. Please, reopen it if that change don't fix the behavior.
