### ISSUE TITLE
Is ipaserver_setup_dns setting always ignored for ipareplica?

### ISSUE THREAD

**Issue by vsevolodZ** [freeipa/ansible-freeipa#526]
I'm installing ipa replica server using ipareplica role.
My settings look like this:

ipaadmin_principal: my_admin_user
ipaadmin_password: my_very_secret_pass
ipareplica_servers: main_ipa_server.my.domain
ipaserver_hostname: ipa_replica.my.domain
ipaserver_setup_dns: yes
ipaserver_auto_forwarders: yes

After playbook successfully finished I have my ipa replica set up, but without dns and without option to install dns manually.

```
ipa-dns-install
ipa-dns-install: command not found
```

```
ipactl status
Directory Service: RUNNING
krb5kdc Service: RUNNING
kadmin Service: RUNNING
httpd Service: RUNNING
ipa-custodia Service: RUNNING
ipa-otpd Service: RUNNING
ipa: INFO: The ipactl command was successful
```

Though during role playbooks execution it has shown me the task ipareplica : Install - Setup DNS with "changed" output.
I've tried this few times with small tweaking (e.g. with and without auto_forwarders) with the same result.

I would expect ipa replica with alternate dns running after applying this role to host, or do I get it wrong?

**Comment by rjeffman** [comment]
`ipa-dns` is a separate package which is not installed if DNS was not setup by the role. That is why you can't run `ipa-dns-install`.

To setup DNS on a replica you should use `ipareplica_setup_dns` (see https://github.com/freeipa/ansible-freeipa/tree/master/roles/ipareplica).

Note that most (if not all) of the variables you want to set for replica start with `ipareplica_`, for example, `ipareplica_forwarders` which you might wan to setup.

**Comment by vsevolodZ** [comment]
Hi, thanks a lot for explanation.
I should've read role's readmes as well.
