### ISSUE TITLE
Installation and configuration documentation not relevant ?

### ISSUE THREAD

**Issue by marcosjl31** [freeipa/ansible-freeipa#533]
Hello

I'm using ansible 2.10.8 and I'd like to relay on freeipa collection to deploy and administer the IPA servers on our lab platform.

Installation information given in the main README.md does not seem to be relevant enough : especially the points concerning the roles/modules/plugins modifications : the roles_path, library and module_utils variable are not loaded properly from te ansible.cfg file (both /etc/ansible/ansible.cfg or ./ansible.cfg; for the latter one, it is related to security concerns as I found on ansible documentation).

Usage documentation is neither very clear : shall I install the collection and then use it by importing the roles ? Shall I clone the collection and then modify or create my specific inventory file ?

I'm quite a newbie using ansible, so I've probably missed something.

Any help or direction will be much appreciated
José

**Comment by flo-renaud** [comment]
Hi,

you can find more documentation here:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/installing_identity_management/installing-an-identity-management-server-using-an-ansible-playbook_installing-identity-management
HTH,
flo

**Comment by marcosjl31** [comment]
Thank you Florence.
