### ISSUE TITLE
Modules terribly slow

### ISSUE THREAD

**Issue by lotusnoir** [freeipa/ansible-freeipa#538]
Hello, 
im using this module and it's working well, but it's terribly slow to process, more or less 1m for each command.

I tried on ansible 2.9.6 and 2.10.
My freeipa version is 4.8.7

I tried with mitogen as well but it's the same result, is it a normal behavior or there is a way to make it faster ?
Kind regards

**Comment by t-woerner** [comment]
Please provide more information.
Which ansible-freeipa version, what parts (plugins or roles) and how have you been using them?
