### ISSUE TITLE
install freeIPA server using this collection as a subdomain of another IPA domain

### ISSUE THREAD

**Issue by t-readyroc** [freeipa/ansible-freeipa#539]
Is it possible to use the ipaserver role to install a freeIPA server as a subdomain CA/DNS of another IPA domain?

**Comment by abbra** [comment]
FreeIPA does not support trust between two IPA deployments, so you cannot achieve what you want with or without ansible-freeipa roles.

**Comment by t-readyroc** [comment]
I actually don't need trust between the deployments, just a signed CA & DNS delegation.

**Comment by abbra** [comment]
DNS delegation would work like in normal DNS setup (e.g. you need to do glue records, as usual).
IPA CA cannot issue sub-CA in the way you want. So it would require you to do manual work where you would first create a special certificate template for that CA cert to sign and then install the other IPA with an external CA, where you would pass a generated certificate request to the first IPA to sign with the use of that profile.
This is most likely need to be performed manually.

**Comment by t-readyroc** [comment]
OK. Was going to try to use the role w/the external CA method, but I'll go ahead manually. Thanks.
