### ISSUE TITLE
Supported distributions

### ISSUE THREAD

**Issue by jumboframezz** [freeipa/ansible-freeipa#573]
It will be great if You add support for rocky and alma linux. Currently ipareplica falls with:
fatal: [ipa-replica-rocky.domain.int]: FAILED! => {"changed": false, "failures": ["freeipa-server All matches were filtered out by modular filtering for argument: freeipa-server"], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}

**Comment by rjeffman** [comment]
@jumboframezz a PR for that support would be welcome.

**Comment by rjeffman** [comment]
Alma and Rocky Linux are supported since PR #627 was merged.
