### ISSUE TITLE
Managing FreeIPA in Docker

### ISSUE THREAD

**Issue by cedws** [freeipa/ansible-freeipa#602]
I was very excited when I found out about this module because the prospect of being able to manage users, hosts, and HBAC rules as code would save me a lot of time. Unfortunately my world was torn apart when I recently found out that we run FreeIPA server in Docker.

Are there any suggestions on how this module could be used in this kind of setup?

Thanks.

**Comment by rjeffman** [comment]
@cedws you might try to use `ansible_connection=docker` in your inventory file. I use a similar approach for `podman` in PR #556.

Also, we are working or PR #575, which would allow ansible-freeipa modules to be executed in client hosts, and this setup might help you.

**Comment by cedws** [comment]
Many thanks, I'll give this a go. Regarding the latter PR, will this mean SSH access to the IPA instance won't be necessary? If the host is in the inventory file then I guess Ansible will always try to connect.

**Comment by rjeffman** [comment]
@cedws, SSH (or another Ansible connection plugin) would still be needed to access an IPA client host, but it would not require SSH (or ther Ansible connection) to the IPA server.

**Comment by cedws** [comment]
Right, sounds exactly like what I'm looking for then, thanks! I'll keep an eye out for this.
