### ISSUE TITLE
`Install - IPA client test` seems to require `six` module for Python3 but it isn't installed

### ISSUE THREAD

**Issue by The-Judge** [freeipa/ansible-freeipa#606]
Hi everyone.

I am trying to apply the `ipaclient` role to a Debian buster node which has Python 3.7.3 installed (package `python3` from default Debian sources).
In `plugins/modules/ipaclient_test.py` there is in lines 195:198 something that looks like a Python2/Python3 differentiation:

```python
try:
    from six.moves.configparser import RawConfigParser
except ImportError:
    from ConfigParser import RawConfigParser
```

So: Since `ConfigParser` has been renamed to `configparser` in Python3, if `six` is not installed, neither `six.moves.configparser.RawConfigParser`, nor `ConfigParser.RawConfigParser` is found.
I also can't find this requirement mentioned anywhere outside of the code.

`ipaclient_install_packages` is `true`; so I would have expected that `python3-six` is installed along with the other requirements for Debian.

**Comment by t-woerner** [comment]
ipaclient requires six. As ipaclient needs to be installed to be able to use the role, six needs to be available.

A new import try for configparser needs to be added though.

**Comment by The-Judge** [comment]
I think this is related to my findings in #607 : Debian package `freeipa-client` pulls in dependencies for Python2 only (including Python2 itself). If one decides to use Python3 as Ansible Python on the remote, the whole thing does not work. It's required to set `ansible_python_interpreter: /usr/bin/python2` somewhere in the group_vars, host_vars, Playbook, ...

I think this is not an exclusive `ansible-freeipa` project-scope issue but a mixed one between Debian FreeIPA-Packaging and this Ansible recipes. No recent package should provide Python2 exclusive support nowadays in my personal opinion, since Python 2 is EOL since January 1st, 2020 and this has been announced since 2008 (see https://www.python.org/doc/sunset-python-2/). But to not open this discussion, I guess the least that should be done from `ansible-freeipa`-project scope is to mention this in the docs.

**Comment by rjeffman** [comment]
With the merge of PR #699 Debian distros have been working, therefore, I'm closing this issue.

If you don't find the fix to be solved, please, reopen it and provide the details.
