### ISSUE TITLE
Fail to resolve module/action 'ipaserver_test'

### ISSUE THREAD

**Issue by bioinfornatics** [freeipa/ansible-freeipa#611]
Dear,
In order to user collection `freeipa.ansible_freeipa` on Rocky-8, I made a minor update.

# Initialization and update
```
$ git clone https://github.com/freeipa/ansible-freeipa.git
$ for i in ansible-freeipa/roles/*/vars; do ln -s RedHat-8.yml Rocky-8.yml; done
```
And I edited the collection version from  ̀galaxy.yml` file

# Build and install
```
$ ansible-galaxy collection build .
$ ansible-galaxy collection install freeipa-ansible_freeipa-0.3.8.tar.gz
```

# Run playbook
```
$ ansible-playbook -vvv -i hosts.yml ~/.ansible/collections/ansible_collections/freeipa/ansible_freeipa/playbooks/install-server.yml
```
Note: I failled to used the playbook without its full path

```
TASK [freeipa.ansible_freeipa.ipaserver : Install IPA server] *****************************************************************************************************************************************************
task path: /home/someone/.ansible/collections/ansible_collections/freeipa/ansible_freeipa/roles/ipaserver/tasks/main.yml:12
fatal: [identity.foo.com]: FAILED! => {
    "reason": "couldn't resolve module/action 'ipaserver_test'. This often indicates a misspelling, missing collection, or incorrect module path.\n\nThe error appears to be in '/home/someone/.ansible/collections/ansible_collections/freeipa/ansible_freeipa/roles/ipaserver/tasks/install.yml': line 60, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install - Server installation test\n  ^ here\n"
}
``` 

As workaround I done this:
``` 
export ANSIBLE_LIBRARY="~/.ansible/plugins/modules/:~/.ansible/collections/ansible_collections/freeipa/ansible_freeipa/roles/ipaserver/library:/usr/share/ansible/plugins/modules/"
```

That seems to works ... but that smell that something is wrong.

Anyway with such workaround that help to process some tasks but that finally fail on task

```
TASK [freeipa.ansible_freeipa.ipaserver : Install - Server installation test]
...
fatal: [identity.foo.com]: FAILED! => {
    "msg": "Could not find imported module support code for ansible.modules.ipaserver_test.  Looked for (['ansible.module_utils.ansible_ipa_server.AnsibleModuleLog', 'ansible.module_utils.ansible_ipa_server'])"
}
```

Any help are welcome

Thanks

Best regards

**Comment by t-woerner** [comment]
There is a script in the utils folder to create the ansible collection for galaxy: `utils/build-galaxy-release.sh`

This script is changing module, module_utils, action_plugin, playbook and also readme files to use the namespace neeed for the collection.

**Comment by bioinfornatics** [comment]
@t-woerner thanks for your help
Now I am able to launch freeipa collection

As I reached another issue, I open a dedicated ticket: #615 

Have a good day

**Comment by t-woerner** [comment]
I think we can close this issue now as the reorted issues are solved.

**Comment by rjeffman** [comment]
PR #627 has been merged and fixes role execution on Rocky Linux, therefore, I'm closing this issue.

If the solution is not enough for the issue, please, reopen it, providing details on what is not fixed yet.
