### ISSUE TITLE
hbacrule_add_host: already a member

### ISSUE THREAD

**Issue by 2342435** [freeipa/ansible-freeipa#617]
Hello,

when i run this playbook:
###
- name: Testplaybook
  hosts: ipam
  gather_facts: no
  tasks:

  - ipahbacrule:
      ipaadmin_password: "{{ vault_ipa_admin_password }}"
      name: testuser_testhost_all
      description: Group testuser_testhost_all
      host: testhost
      user: testuser
      servicecategory: all
    run_once: true
###

On first run, the host will be added. On second run it will be removed. On third it will be added...

When i change the playbooks top to:
###
- name: Testplaybook
  hosts: ipam,ipa01
  gather_facts: no
  tasks:
###

So that it is run on more than one host, i will get:
fatal: [ipa01]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3.6"}, "changed": false, "msg": "hbacrule_add_host: host testhost.testdomain.de: This entry is already a member"}      

When i use "hostgroup" instead of "host" everything seems to be fine.

Regards

Sören

**Comment by t-woerner** [comment]
I can confirm this issue.
