### ISSUE TITLE
sudo issue,  user NOT in sudoers ;

### ISSUE THREAD

**Issue by kaz-33** [freeipa/ansible-freeipa#642]
Hello Team,
after enrollment client, i can't run the sudo command without some manual command.

CentOS Linux release 8.3.2011
Ansible galaxy freeipa 0.3.6, 0.3.8

Workarround:
/etc/nsswitch.conf
add --> **sudoers: ldap sss files**

/etc/sssd/sssd.conf [sssd]
add --> services = nss, pam, ssh, **sudo**

clean cache
sss_cache -E
systemctl stop sssd
rm -fr /var/lib/sss/db/*
systemctl start sssd

Any idea, why i need to do that?
thanks for the great job.
Br

**Comment by t-woerner** [comment]
Have you set `ipaclient_no_sudo` to `yes`?

**Comment by kaz-33** [comment]
got it, it was a stupid copy/past...
Thx
