### ISSUE TITLE
ipaserver: "Could not find imported module support code for ipaserver_test.  Looked for either *.py or ansible_ipa_server.py"

### ISSUE THREAD

**Issue by silanea** [freeipa/ansible-freeipa#68]
Ansible host: FC28, Ansible v. 2.7.9, Python 2.7.15/3.6.8
Target: FC29, Python 3.7.2
Commit: #387f555

Running install-server.yml (with both ansible-playbook-2 and ansible-playbook-3) gives:
`TASK [ipaserver : Install - Server installation test] *********************************************************************************************************************************************************
task path: /etc/ansible/roles/ipaserver/tasks/install.yml:28
<target> ESTABLISH SSH CONNECTION FOR USER: ansible-user
<target> SSH: EXEC sshpass -d9 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o User=ansible-user -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/fa531c6114 target '/bin/sh -c '"'"'echo ~ansible-user && sleep 0'"'"''
<target> (0, '/home/ansible-user\n', 'OpenSSH_7.8p1, OpenSSL 1.1.0i-fips  14 Aug 2018\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug3: /etc/ssh/ssh_config line 52: Including file /etc/ssh/ssh_config.d/05-redhat.conf depth 0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/05-redhat.conf\r\ndebug3: /etc/ssh/ssh_config.d/05-redhat.conf line 2: Including file /etc/crypto-policies/back-ends/openssh.config depth 1\r\ndebug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config\r\ndebug3: gss kex names ok: [gss-gex-sha1-,gss-group14-sha1-]\r\ndebug3: kex names ok: [curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1]\r\ndebug1: /etc/ssh/ssh_config.d/05-redhat.conf line 8: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 12344\r\ndebug3: mux_client_request_session: session request sent\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<target> ESTABLISH SSH CONNECTION FOR USER: ansible-user
<target> SSH: EXEC sshpass -d9 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o User=ansible-user -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/fa531c6114 target '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/ansible-user/.ansible/tmp/ansible-tmp-1554476429.16-190527893568211 `" && echo ansible-tmp-1554476429.16-190527893568211="` echo /home/ansible-user/.ansible/tmp/ansible-tmp-1554476429.16-190527893568211 `" ) && sleep 0'"'"''
<target> (0, 'ansible-tmp-1554476429.16-190527893568211=/home/ansible-user/.ansible/tmp/ansible-tmp-1554476429.16-190527893568211\n', 'OpenSSH_7.8p1, OpenSSL 1.1.0i-fips  14 Aug 2018\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug3: /etc/ssh/ssh_config line 52: Including file /etc/ssh/ssh_config.d/05-redhat.conf depth 0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/05-redhat.conf\r\ndebug3: /etc/ssh/ssh_config.d/05-redhat.conf line 2: Including file /etc/crypto-policies/back-ends/openssh.config depth 1\r\ndebug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config\r\ndebug3: gss kex names ok: [gss-gex-sha1-,gss-group14-sha1-]\r\ndebug3: kex names ok: [curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1]\r\ndebug1: /etc/ssh/ssh_config.d/05-redhat.conf line 8: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 12344\r\ndebug3: mux_client_request_session: session request sent\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
fatal: [target]: FAILED! => {
    "msg": "Could not find imported module support code for ipaserver_test.  Looked for either *.py or ansible_ipa_server.py"`

**Comment by t-woerner** [comment]
Please update to 0b5b5756c70402ed2e5bc92e0b83118c200d2222.

**Comment by silanea** [comment]
Same result. Other roles outside of this repo run fine on the machine, though they also give the 'broken pipe' messages. No hints in the target's logs, either.

**Comment by t-woerner** [comment]
ansible_ipa_server.py is not found, but it is in the ipaserver role. How have you transferred the roles to the controller?

**Comment by silanea** [comment]
Could not reproduce with a clean checkout, possibly a fluke. If it comes back, I'll post info.
