### ISSUE TITLE
No DNS label

### ISSUE THREAD

**Issue by LucaPrete** [freeipa/ansible-freeipa#75]
Hi guys,

During the freeipa replica installation I get the following error:

fatal: [ipareplica01]: FAILED! => {"changed": false, "msg": "empty DNS label"}

Anyone knows what's this about and how could I solve it?

Thanks

**Comment by t-woerner** [comment]
In which installation step is this happening? Is the domain or the realm name empty?

**Comment by LucaPrete** [comment]
I can give it a try again to see the output.
It happens during the replica installation. Can't remember precisely at
what point.

I've tried whatever was written in the ansible options. Right now the
inventory has the following variables:
ipaservers, ipaadmin_password, ipadm_password, ipaclient_domain,
ipaclient_realm

Il giorno mar 23 apr 2019 alle ore 12:50 Thomas Woerner <
notifications@github.com> ha scritto:

**Comment by LucaPrete** [comment]
Specifically, this is what happens:

```
...
TASK [ipaclient : Set python interpreter to 3] ***********************************************************************************************************************************************************************************************
skipping: [ipareplica01]
skipping: [ipareplica02]

TASK [ipaclient : Set python interpreter to 2] ***********************************************************************************************************************************************************************************************
ok: [ipareplica01]
ok: [ipareplica02]

TASK [ipaclient : Install - Set ipaclient_servers] *******************************************************************************************************************************************************************************************
skipping: [ipareplica01]
skipping: [ipareplica02]

TASK [ipaclient : Install - Set ipaclient_servers from cluster inventory] ********************************************************************************************************************************************************************
skipping: [ipareplica01]
skipping: [ipareplica02]

TASK [ipaclient : fail] **********************************************************************************************************************************************************************************************************************
skipping: [ipareplica01]
skipping: [ipareplica02]

TASK [ipaclient : Install - Set default principal if no keytab is given] *********************************************************************************************************************************************************************
skipping: [ipareplica01]
skipping: [ipareplica02]

TASK [ipaclient : Install - IPA client test] *************************************************************************************************************************************************************************************************
fatal: [ipareplica02]: FAILED! => {"changed": false, "msg": "empty DNS label"}
fatal: [ipareplica01]: FAILED! => {"changed": false, "msg": "empty DNS label"}
  to retry, use: --limit @/Users/XXX/work/yyy-ansible/ansible-freeipa/install-replica.retry

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
ipareplica01               : ok=13   changed=1    unreachable=0    failed=1
ipareplica02               : ok=13   changed=1    unreachable=0    failed=1
```

**Comment by t-woerner** [comment]
Which FreeIPA version any system are you using?

**Comment by t-woerner** [comment]
I have not seen this error before. validate_dns_label is used in validate_domain_name or validate_hostname. I am only able to get "empty DNS label" if there is a leading "." in either hostname or domain name.

**Comment by LucaPrete** [comment]
Unfortunately it wasn’t the case...I’ve checked multiple times and then I
had to give up.

I had anyway to move to custom roles since the repo wasn’t tagged and it
wasn’t compatible with Galaxy.

-Luca

Il giorno ven 3 mag 2019 alle 15:15 Thomas Woerner <notifications@github.com>
ha scritto:

**Comment by t-woerner** [comment]
Please have a look at the anisble_freeipa collection in galaxy. It is providing the roles and also additional modules for management.

**Comment by LucaPrete** [comment]
Thank you Thomas.

-Luca

Il giorno mar 30 lug 2019 alle ore 12:01 Thomas Woerner <
notifications@github.com> ha scritto:

**Comment by t-woerner** [comment]
@LucaPrete Have you been able to find out, what the issue was with the host or domain name?

**Comment by LucaPrete** [comment]
Thomas, unfortunately, we have not.
We had to quickly move to something else, so we lost the focus on this
specific issue.

-Luca

Il giorno ven 15 nov 2019 alle ore 16:58 Thomas Woerner <
notifications@github.com> ha scritto:

**Comment by t-woerner** [comment]
This issue is not reproducible. Please reopen the ticket if you run into it again.
