### ISSUE TITLE
 [RFE] Missing module to manage ID views

### ISSUE THREAD

**Issue by rjeffman** [freeipa/ansible-freeipa#803]
As a FreeIPA administrator, I want to manage ID views using ansible-freeipa.

Related CLI commands:
* idview-add
* idview-del
* idview-mod
* idview-unapply
* idview-apply
* idview-find
* idview-show

**Comment by myllynen** [comment]
I came across this today so, FWIW, this would be helpful to have, yes. For reference here's the RHEL IdM documentation about ID views:

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/managing_idm_users_groups_hosts_and_access_control_rules/using-an-id-view-to-override-a-user-attribute-value-on-an-idm-client_managing-users-groups-hosts

Thanks.

**Comment by rjeffman** [comment]
@myllynen we are looking for a way to publish our roadmap, and extending support for AD trust configuration is to be implemented in the next months.

**Comment by myllynen** [comment]
Thanks, roadmap sounds very nice to have! I'm going to assume you mixed ID overrides and ID views a bit as there are use cases for ID views also without AD trust in place.

**Comment by rjeffman** [comment]
Yes, I've "mixed" them, because usually I've seen issues with ID views when related to AD trust. That's why they'll be implemented around the same time. For similar reasons, we only tackled ID range after we started to work on AD trusts.
