### ISSUE TITLE
Add support for creating indirect automount maps

### ISSUE THREAD

**Issue by Thulium-Drake** [freeipa/ansible-freeipa#804]
The docs over at https://github.com/freeipa/ansible-freeipa/blob/master/README-automountmap.md now mention that creating indirect mountpoints is not supported.

I'm working on a playbook that configures (among others) a automountmap for home directories. And from what I know, those should be indirect maps (as they are more flexible and don't require restarting the autofs daemon on each change).

What is stopping the module from creating indirect maps?

**Comment by Thulium-Drake** [comment]
Maybe a stupid question...

Currently I am running the following tasks:

- Create a map file -> ```auto.home```
- Create a key for ```/home``` in ```auto.master```
- Create a key for ```*``` in ```auto.home``` that points to ```nfs.example.com:/exports/home&```

Isn't that basically the same as what the wizard in the UI does when I'm creating an indirect map? Or are they also treated differently?

**Comment by rjeffman** [comment]
Automount maps are still not supported because we did not agreed on how the playbook interface for indirect automount maps should look like.

I'm far from an expert on automount, and as far as I understood, they are treated differently. And I might be completely wrong on this matter.

**Comment by rjeffman** [comment]
Link to RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=2050176

**Comment by Thulium-Drake** [comment]
After using the IdM server I have provisioned with the procedure in my previous post a while. It seems to work 'just fine (tm)'. So we may not need to also be able to make indirect maps.

Can someone else also please give it a shot? :-)

**Comment by rjeffman** [comment]
@Thulium-Drake, as we aim to full compatibility with FreeIPA CLI tools, this will be added to ansible-freeipa at some point in the future. Maybe in the not so distant future, so that we can have the complete automount support and focus on other areas.

We are still deciding on how the playbook interface will work for indirect maps, once it is done, implementation is somewhat simple.
