### ISSUE TITLE
[ipareplica] no pki-tomcatd service after installation ?

### ISSUE THREAD

**Issue by marcosjl** [freeipa/ansible-freeipa#806]
Dear all,

**Versions**
```
OS (server/replica) : Centos 7.9 (final)
ipa* RPM : 4.6.8-5 
ansible : 2.12.4
freeipa.ansible_freeipa collection : 1.6.2
```
**Inventory file**
No DNS or NTP in IPA - thoses services are provided externally.

```
[ipaserver]
tu-ipa1-p01.robotics.cst.cnes.fr

[ipaserver:vars]
# No DNS managed by IPA.
ipaserver_setup_dns=no
ipaserver_auto_forwarders=no
ipaserver_setup_firewalld=no
ipaclient_no_ntp=yes



[ipareplicas]
tu-ipa2-p01.robotics.cst.cnes.fr

[ipareplicas:vars]
ipaclient_no_ntp=yes


[ipaclients]
tu-hebe-p01.robotics.cst.cnes.fr ansible_host=10.160.7.210 ipaclient_servers=tu-ipa1-p01.robotics.cst.cnes.fr,tu-ipa2-p01.robotics.cst.cnes.fr

[ipaclients:vars]
ipaclient_force_join=yes
ipaclient_allow_repair=yes

[ipacluster:children]
ipaserver
ipareplicas
ipaclients

[ipacluster:vars]
ipaadmin_principal=admin
ipaserver_domain=robotics.cst.cnes.fr
ipaserver_realm=ROBOTICS.CST.CNES.FR
```

**Problem / question**
I manage to successfully (or so I think)  install server, replica and client... But when I do an ipactl status, iI do not get the same list of services on both server and replica instances, as shown here after.
I don't know if this is a normal configuration - I don't think so after googling on this topic : list of services should be the same on both IPA server and replica. I've checked all logs available on replica side, but no success so far.

Any hint appreciated !

* On IPA server : 

```
tu-ipa1-p01# ipactl status
Directory Service: RUNNING
krb5kdc Service: RUNNING
kadmin Service: RUNNING
httpd Service: RUNNING
ipa-custodia Service: RUNNING
pki-tomcatd Service: RUNNING
ipa-otpd Service: RUNNING
ipa: INFO: The ipactl command was successful
```
* On replica server
```
tu-ipa2-p01# ipactl status
Directory Service: RUNNING
krb5kdc Service: RUNNING
kadmin Service: RUNNING
httpd Service: RUNNING
ipa-custodia Service: RUNNING
ipa-otpd Service: RUNNING
ipa: INFO: The ipactl command was successful
```

**Comment by abbra** [comment]
This is normal because CA replica is optional. I'd recommend you to read RHEL IdM documentation that explains how this works.
For ansible-freeipa, there are explicit configuration variables you'd should be using to specify which optional services would need to be present on the replica.

`ipa-replica-install` man page has this:
```
   CERTIFICATE SYSTEM OPTIONS
       --setup-ca
              Install and configure a CA on this replica. If a CA is not configured then certificate operations will be forwarded to a master with a CA installed.
```

**Comment by marcosjl** [comment]
Thank you for the clarification.

I understand that "no CA replica" is not an issue in case of IPA master server being OFF ? 
I am going to read IdM documentation.

Rgds
José

**Comment by abbra** [comment]
It is fully up to you how you'd design your deployment topology. There are some recommendations as to how many replicas to have for both primary data and CA domains. They aren't necessarily have the same requirements and there is definitely no need to have 1:1 mapping between primary data and CA domain replicas. That is a reason why CAs are optional on IPA replicas.

**Comment by flo-renaud** [comment]
Hi,

a good read would be
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/planning_identity_management/planning-your-ca-services-planning-identity-management#guidelines-for-the-distribution-of-ca-services_planning-ca

If you have only one server providing the CA role and he's down, you won't
be able to issue new certificates, revoke existing ones etc...

flo

**Comment by marcosjl** [comment]
I've managed to install the replica CA, by defining 'ipareplica_setup_ca=yes' in the [ipareplica:vars] section.

After installation and configuration, pki-tomcatd Service is running as well on the replica machine.
