### ISSUE TITLE
CA certificate is expired

### ISSUE THREAD

**Issue by farazbyk** [freeipa/ansible-freeipa#814]
My FreeIPA server CA certificate is expired, how it can be renewed because it stopped working on browser plus i can't login to admin using ansible.
Somehow the user authentication is still currently working 

[Thu Apr 2022] [:error] [pid 2660] SSL Library Error: -8181 Certificate has expired
[Thu Apr 21 2022] [:error] [pid 2660] Unable to verify certificate 'Server-Cert'. Add "NSSEnforceValidCerts off" to nss.conf so the server can start until the problem can be resolved.

I managed to start the server but it stopped authentication for admin as well through browser.

Also I renew status is true but CA has not renewed 

status: MONITORING
	ca-error: Error setting up ccache for "host" service on client using default keytab: Keytab contains no suitable keys for host/ipa1.example.com@.
	stuck: no
	key pair storage: type=NSSDB,location='/etc/dirsrv/slapd-EXAMPLE-COM',nickname='Server-Cert',token='NSS Certificate DB',pinfile='/etc/dirsrv/slapd-EXAMPLE-COM/pwdfile.txt'
	certificate: type=NSSDB,location='/etc/dirsrv/slapd-EXAMPLE-COM',nickname='Server-Cert',token='NSS Certificate DB'
	CA: IPA
	issuer: CN=Certificate Authority,O=EXAMPLE.COM
	subject: CN=ipa1.example.com,O=EXAMPLE.COM
	expires: 2022-04-13 11:58:18 UTC
	dns: ipa1.example.com
	principal name: ldap/ipa1.example.com@EXAMPLE.COM
	key usage: digitalSignature,nonRepudiation,keyEncipherment,dataEncipherment
	eku: id-kp-serverAuth,id-kp-clientAuth
	pre-save command: 
	post-save command: /usr/libexec/ipa/certmonger/restart_dirsrv EXAMPLE-COM
	track: yes
	auto-renew: yes

**Comment by farazbyk** [comment]
@rjeffman issue got fixed by using ipa-cert-fix utility

**Comment by rjeffman** [comment]
@farazbyk good to know.
