### ISSUE TITLE
ipaclient role: add ```*_homedir``` configuration options

### ISSUE THREAD

**Issue by Thulium-Drake** [freeipa/ansible-freeipa#823]
Hi!

I'm trying to integrate an IdM/IPA setup with AD and I'm having some issues reading the ```homeDirectory``` attribute from AD in Linux (so it matches the actual situation).

However, it seems that attribute is not available (same goes for ```mail```) when querying for that user using ```getent```:

AD attributes:
![image](https://user-images.githubusercontent.com/12935477/166207403-97221579-4adb-452f-816d-b2c18ef9f52a.png)
What the IdM server sees:
![image](https://user-images.githubusercontent.com/12935477/166207434-9a92acfb-4b96-4ded-b79e-c1c743fe90cf.png)

But, I have succesfully been able to override it (without breaking existing IdM users) using ```subdomain_homedir```.

However, it seems to me that the other ones (```fallback_homedir```, ```override_homedir```) can also be very useful to have available in the ```ipaclient``` role.

EDIT: hmm, after looking some more in the AD properties of this user (I'm not an AD expert), it seems that the ```homeDirectory``` is actually used by the Windows environment... But the ```unixHomeDirectory``` isn't used at all. So, that makes this request even more important for AD integrated environments :-)

**Comment by abbra** [comment]
Neither FreeIPA nor ansible-freeipa manage SSSD settings related to this.
SSSD automatically derives these properties from AD and takes ID Overrides on IPA side into account, if needed.
SSSD looks at Global Catalog, so check if POSIX attributes in AD LDAP synchronized to Global Catalog (they might be not there by default).

**Comment by Thulium-Drake** [comment]
I checked the GC on the AD side, it seems that the ```unixHomeDirectory``` attribute is not there, so it will probably not show up on the IdM side of things. However, it's fine that's missing, as it can be fixed by setting ```subdomain_homedir``` on the SSSD side.

Which also fixes it for users that don't have a homedirectory set in AD (which is the case in my environment, as we're integrating Linux and AD for the first time).

Therefore I think it's useful that the ```ipaclient``` role can manage ```subdomain_homedir``` as well. Do you agree?

**Comment by abbra** [comment]
ansible-freeipa attempts to handle feature parity with FreeIPA itself. We do not plan to add management of SSSD configuration to FreeIPA, so I do not see a valid reason to add it here as well. A separate SSSD configuration management role, might be.

Regarding the rewrite of defaults in a centralized way, there is a plan to add global and per-domain defaults to ID Overrides in FreeIPA. I have a branch that adds IPA API for that but it needs corresponding support from SSSD side which is planned to be worked on later this year. This would allow to avoid these issues completely by setting an ID override for the whole domain in IPA and letting SSSD to inherit it to all accounts, without individual ID overrides.

**Comment by Thulium-Drake** [comment]
Sounds reasonable, but awesome to hear that it will be possible to manage this using ID overrides \o/

As this is then covered by your answers, I'll close this :-) thank you!
