### ISSUE TITLE
freeipa roles should rename state variable to avoid conflicts

### ISSUE THREAD

**Issue by ikke-t** [freeipa/ansible-freeipa#824]
I hunted down problem in AAP for quite a while. It was eventually by me adding workflow variable called ```state``` to reflect VM state. That then leaked to job_template for adding VM to IDM. Even thought I had ```state: present``` set for the ipaclient role, the global variable overrode it to "poweredon".

It was my mistake. But it could have helped if ipaclient (and the server etc...) roles would follow the best practises of having role name in front of such variables.

So ```state``` variable should be e.g. ```ipaclient_state``` as per [best practices](https://redhat-cop.github.io/automation-good-practices/#_naming_things):

**Comment by t-woerner** [comment]
The parameter `state` is more or less a standard parameter and used by Ansible provided modules (example: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html#parameter-state and https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_module.html#parameter-state) and also several of the roles in [linux-system-roles](https://github.com/linux-system-roles) (example: https://github.com/linux-system-roles/network#state, https://github.com/linux-system-roles/firewall#state, https://github.com/linux-system-roles/selinux#usage).

I prefer to have the naming of this parameter consistent to Ansible modules and roles in linux-system-roles.
