### ISSUE TITLE
"module enable idm:DL1" dependency missing in Rhel8 deployment

### ISSUE THREAD

**Issue by PA7R14RCH** [freeipa/ansible-freeipa#861]
I don't want to waist anyone's time. The README indicates Rhel 7.4 + but I'm not sure if that means Rhel 8 release.

Under the IPASERVER role in the install.yml the first task "Ensure that IPA server packages are installed" requires the IDM:DL1 module to be enable to access ipa-server install and therefore fails. 

Does this role support Rhel8 and latest Ansible Core? I have stumbled into a few other variables within Ansible as well. Before I get to far down the hole, I want to verify. 

-RedHat 8.6 release
-Ansible core version 2.12.2
-Python version 3.8.12

**Comment by rjeffman** [comment]
Yes, these roles and plugins support RHEL 8 and RHEL 9.

You may want to check [Installing an Identity Management server using an Ansible playbook](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/installing_identity_management/installing-an-identity-management-server-using-an-ansible-playbook_installing-identity-management). As for RHEL 8.6, and if you want to use `ansible-core`, you should ignore section `29.2` on this document.

Remember that Ansible is only required on the controller, and it don't need to be a RHEL machine.

On Red Hat based distros (Fedora, CentOS and RHEL), these roles are also available as the RPM package `ansible-freeipa`

**Comment by rjeffman** [comment]
As this is not an issue, and an answer is available I'm closing this.

Please, reopen the issue if the provided answer is not sufficient.
