### ISSUE TITLE
Syntax error: `logger.info()`

### ISSUE THREAD

**Issue by jpclipffel** [freeipa/ansible-freeipa#865]
Hi,

## Problem description

Calling the role `freeipa.ansible_freeipa.ipaclient` fails with the following error:

```
Traceback (most recent call last):
  File "/home/user/.ansible/tmp/ansible-tmp-1658911755.3492198-42309-80739609628500/AnsiballZ_ipaclient_test.py", line 102, in <module>
    _ansiballz_main()
  File "/home/user/.ansible/tmp/ansible-tmp-1658911755.3492198-42309-80739609628500/AnsiballZ_ipaclient_test.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/user/.ansible/tmp/ansible-tmp-1658911755.3492198-42309-80739609628500/AnsiballZ_ipaclient_test.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.freeipa.ansible_freeipa.plugins.modules.ipaclient_test', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_freeipa.ansible_freeipa.ipaclient_test_payload_vtgensu6/ansible_freeipa.ansible_freeipa.ipaclient_test_payload.zip/ansible_collections/freeipa/ansible_freeipa/plugins/modules/ipaclient_test.py", line 941, in <module>
  File "/tmp/ansible_freeipa.ansible_freeipa.ipaclient_test_payload_vtgensu6/ansible_freeipa.ansible_freeipa.ipaclient_test_payload.zip/ansible_collections/freeipa/ansible_freeipa/plugins/modules/ipaclient_test.py", line 883, in main
TypeError: info() missing 1 required positional argument: 'msg'
fatal: [testhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to 1.2.3.4 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/user/.ansible/tmp/ansible-tmp-1658911755.3492198-42309-80739609628500/AnsiballZ_ipaclient_test.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/user/.ansible/tmp/ansible-tmp-1658911755.3492198-42309-80739609628500/AnsiballZ_ipaclient_test.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/user/.ansible/tmp/ansible-tmp-1658911755.3492198-42309-80739609628500/AnsiballZ_ipaclient_test.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.freeipa.ansible_freeipa.plugins.modules.ipaclient_test', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_freeipa.ansible_freeipa.ipaclient_test_payload_vtgensu6/ansible_freeipa.ansible_freeipa.ipaclient_test_payload.zip/ansible_collections/freeipa/ansible_freeipa/plugins/modules/ipaclient_test.py\", line 941, in <module>\r\n  File \"/tmp/ansible_freeipa.ansible_freeipa.ipaclient_test_payload_vtgensu6/ansible_freeipa.ansible_freeipa.ipaclient_test_payload.zip/ansible_collections/freeipa/ansible_freeipa/plugins/modules/ipaclient_test.py\", line 883, in main\r\nTypeError: info() missing 1 required positional argument: 'msg'\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

## Environment

* The collection `freeipa.ansible_freeipa` has been installed using `ansible-galaxy collection install freeipa.ansible_freeipa`
* The collection has been installed in its latest version (`1.8.1` as of today)
* The role `freeipa.ansible_freeipa.ipaclient` is called either directly from a playbook or using `ansible.builtin.include_role`

Direct call (example):

```ansible
hosts: all
roles:
  - freeipa.ansible_freeipa.ipaclient
```

Called through `include_role` (simplified example):

```ansible
- name: Install IPAClient
  ansible.builtin.include_role:
    role_name: "freeipa.ansible_freeipa.ipaclient"
```

## Analysis

This error seems to appears in different locations:

* In the collection **package** (hosted on Ansible Galaxy):
  * `plugins/modules/ipaclient_test.py` at line `883`
  * `roles/ipaclient/library/ipaclient_test.py` at line `883`
* In the collection **source** (hosted in the repository):
  * `roles/ipaclient/library/ipaclient_test.py` at line `883`

The following code snippet shows the error:

```python
if is_ipaddr:
    logger.info()
    logger.warning(
        "It seems that you are using an IP address "
        "instead of FQDN as an argument to --server. The "
        "installation may fail.")
    break
```

## Resolution

This issue is trivial to patch (simply remove the line `logger.info()` and its done), however I'm not sure why the collection source code on GitHub and the package source code (as downloaded from Ansible Galaxy) seems to differ (the responsible file in the collection package is `plugins/modules/ipaclient_test.py` and it does not exists in the repository source).

Could it be the that the collection building process or your workflows move / copy the file `ipaclient_test.py` ?

**Comment by t-woerner** [comment]
Thanks for the report. Yes, the use of logger.info() in ipaclient_test.py is a bug and needs to be fixed.
In an Ansible collection all plugins need to be placed in the collection global plugins folder to be able to be found, also the ones that belong to a role only and are only usable within the role.

**Comment by t-woerner** [comment]
It would be good to use FQDN servers though as the use of IP addresses might result in issues later on.

**Comment by jpclipffel** [comment]
> Thanks for the report. Yes, the use of logger.info() in ipaclient_test.py is a bug and needs to be fixed. In an Ansible collection all plugins need to be placed in the collection global plugins folder to be able to be found, also the ones that belong to a role only and are only usable within the role.

Thank you for your answer :)

After reviewing your script `utils/build-galaxy-release.sh`, am I right to assume that the only file to patch is `roles/ipaclient/library/ipaclient_test.py`, as `build-galaxy-release.sh` will properly generate/patch/update the Molecule resources and the collection plugins ?

**Comment by t-woerner** [comment]
Yes, only `roles/ipaclient/library/ipaclient_test.py` needs to be changed.

**Comment by jpclipffel** [comment]
Thanks.
MR created: https://github.com/freeipa/ansible-freeipa/pull/867

**Comment by rjeffman** [comment]
@jpclipffel thank you for the fix.

Closing this issue as the PR has been merged.
