### ISSUE TITLE
[RFE] Allow making primary server hidden

### ISSUE THREAD

**Issue by myllynen** [freeipa/ansible-freeipa#872]
In some cases it would be helpful if the primary server (especially in case of CA enabled) would be allowed to hidden instead of "regular" replicas. Currently the roles allow making replicas hidden but not the primary server. Please consider this request if technically feasible. Thanks.

**Comment by rjeffman** [comment]
You cannot hide the CA renewal master. This is a limitation on FreeIPA, so it is something that we will never allow, until FreeIPA allows it.

**Comment by myllynen** [comment]
Thanks for pointing that out, I think it's best to close this one and reopen in case such a change ever happens although the chances look low. Thanks.

**Comment by rjeffman** [comment]
As a simple example, this is what IPA CLI returns if I try to hide my only `ipaserver`:
```
Cannot hide CA renewal master. Cannot hide last enabled CA server. Cannot hide last enabled DNS server. Cannot hide last enabled IPA server. Cannot hide last enabled KRA server.
```

So, in any of these cases (there might be more cases, e.g. with an AD trust), there is nothing that `ansible-freeipa` can do about it.
