### ISSUE TITLE
[RFE] Allow multiple groups creation

### ISSUE THREAD

**Issue by myllynen** [freeipa/ansible-freeipa#879]
ipauser allows creating/deleting multiple users in one go and ipagroup allows deleting multiple groups in one operation.

In some cases it would speed things up if multiple groups could be created with one operation.

Thanks.

**Comment by rjeffman** [comment]
There is a workaround to have a TGT available on the target host for the `admin` user, which speeds up authentication:
```
tasks:
- shell: echo SomeADMINpassword | kinit admin
(add your ipa* tasks)
- shell: kdestroy -A
```
This would be similar to a group module that allows the use of multiple groups, and might be used until this RFE is implemented.
