### ISSUE TITLE
vars for RHEL 9

### ISSUE THREAD

**Issue by hakong** [freeipa/ansible-freeipa#888]
Hi,
I noticed there's no vars file for RHEL 9. Is there anything else to be done for RHEL 9 support other than adding the vars file like for RHEL 8 (except the module names don't work anymore)?

I can make a PR if this is all that's needed.

**Comment by rjeffman** [comment]
@hakong RHEL 9 is supported without any change needed to the source. Although specific vars are not set for the deployment roles, the `default` works for IPA deploy on RHEL 9.

As RHEL 9 is already supported I'm closing this issue. If you find any error while using ansible-freeipa to manage IPA on RHEL 9, please, open another issue reporting your findings.

**Comment by hakong** [comment]
Thanks for clarifying this, I just noticed that our custom RedHat-9.yml was being included instead of the main.yml default. That explains the undefined variable ipaclient_packages error I was getting.
