### ISSUE TITLE
Invalid RID/SID SSSD backtrace after deployment

### ISSUE THREAD

**Issue by myllynen** [freeipa/ansible-freeipa#896]
This might well be a user error so please bear me with.

I have deployed IPA/IdM using the playbooks at https://github.com/myllynen/rhel-idm-automation where the only UID/GID/SID/RID related settings are the following (I'd hope these are suitable for testing purposes):

```
# UID/GID range
ipaserver_idstart: 1000
ipaserver_idmax: 999999
```

After joining a client to the domain I see SSSD logging this error in sssd_sub.example.com.log:

(2022-08-30 15:16:01): [be[sub.example.com]] [server_setup] (0x1f7c0): Starting with debug level = 0x0070
(2022-08-30 15:16:01): [be[sub.example.com]] [sysdb_range_create] (0x0040): [RID#1] Invalid range, skipping. Expected that either the secondary base RID or the SID of the trusted domain is set, but not both or none of them.
********************** PREVIOUS MESSAGE WAS TRIGGERED BY THE FOLLOWING BACKTRACE:
...
   *  (2022-08-30 15:16:01): [be[sub.example.com]] [sdap_parse_range] (0x2000): [RID#1] No sub-attributes for [ipaRangeType]
   *  (2022-08-30 15:16:01): [be[sub.example.com]] [sdap_process_result] (0x2000): Trace: sh[0x55f96b4db1f0], connected[1], ops[0x55f96b4d1eb0], ldap[0x55f96b4da590]
   *  (2022-08-30 15:16:01): [be[sub.example.com]] [sdap_process_message] (0x4000): [RID#1] Message type: [LDAP_RES_SEARCH_RESULT]
   *  (2022-08-30 15:16:01): [be[sub.example.com]] [sdap_get_generic_op_finished] (0x0400): [RID#1] Search result: Success(0), no errmsg set
   *  (2022-08-30 15:16:01): [be[sub.example.com]] [sdap_op_destructor] (0x2000): [RID#1] Operation 5 finished
   *  (2022-08-30 15:16:01): [be[sub.example.com]] [sdap_search_bases_ex_done] (0x0400): [RID#1] Receiving data from base [cn=ranges,cn=etc,dc=sub,dc=example,dc=com]
   *  (2022-08-30 15:16:01): [be[sub.example.com]] [sysdb_update_ranges] (0x0400): [RID#1] Adding range [SUB.EXAMPLE.COM_id_range].
   *  (2022-08-30 15:16:01): [be[sub.example.com]] [sysdb_range_create] (0x0040): [RID#1] Invalid range, skipping. Expected that either the secondary base RID or the SID of the trusted domain is set, but not both or none of them.
********************** BACKTRACE DUMP ENDS HERE *********************************

It is unclear to me currently is this perhaps due to invalid configuration parameters passed to the ansible-freeipa or ansible-freeipa setting something incorrect or FreeIPA itself doing something incorrectly? According to the ansible-freeipa documentation I don't immediately see anything that would explain this.

Thanks.

**Comment by t-woerner** [comment]
Which ansible-freeipa and ipa version was used?

**Comment by myllynen** [comment]
Yes, good point. This is on RHEL 9 with all the available patches applied, ansible-freeipa from RHEL repo. Thanks.

**Comment by t-woerner** [comment]
It seems there is a missing check in ansible-freeipa ipaserver role for idstart.

Using the command line installer with idstart=1000 results in: 

> ipa-server-install: error: idstart (1000) must be larger than UID_MAX/GID_MAX (60000) setting in /etc/login.defs.

Are you running into this issue also if you are using `ipaserver_idstart: 60000` ?

**Comment by myllynen** [comment]
Thanks for looking into this.

Even after bumping idstart I still see the same backtrace. Here's the `ipa idrange-find` output:

```
# ipa idrange-find
----------------
2 ranges matched
----------------
  Range name: SUB.EXAMPLE.COM_id_range
  First Posix ID of the range: 100000
  Number of IDs in the range: 900000
  Range type: local domain range

  Range name: SUB.EXAMPLE.COM_subid_range
  First Posix ID of the range: 2147483648
  Number of IDs in the range: 2147352576
  First RID of the corresponding RID range: 2146583648
  Domain SID of the trusted domain: S-1-5-21-738065-838566-300686332
  Range type: Active Directory domain range
----------------------------
Number of entries returned 2
----------------------------
```

Thanks.

**Comment by t-woerner** [comment]
Please provide the output of `rpm -q ansible-freeipa`.

Where do you have this issue, on the client, server or a replica? I tried to verify the issue, but was not able to see this.

If possible, please try to use latest ansible-freeipa 1.8.3 as there have been changes related to SIDs for servers and replicas.

**Comment by myllynen** [comment]
Sorry for the confusion, this is actually on RHEL 8 - not RHEL 9 - with latest updates. All of Ansible Control Node, IdM servers and IdM client are RHEL 8. I see this on all of server/replica/client. This is not related to initial installation as I can stop SSSD, remove all SSDS logs, and start SSSD and still see the issue in the log.

```
# rpm -q ansible-freeipa
ansible-freeipa-1.6.3-1.el8.noarch
```

I will retry with the latest ansible-freeipa in a day or two and will report the results here. Thanks.

**Comment by t-woerner** [comment]
That is great, thank you.

**Comment by t-woerner** [comment]
With ansible-freeipa version 1.6.3 SIDs have not been enabled at deploy time and therefore they are not generated. The command `ipa config-mod --enable-sid --add-sids` can be used to fix this in the existing domain. After this command has been used, the issue is not reported any more in the logs.
