### ISSUE TITLE
[RFE] ipasudorule category missing

### ISSUE THREAD

**Issue by myllynen** [freeipa/ansible-freeipa#898]
IPA/IdM WebUI shows the following for sudo rule:

As Whom
RunAs User category the rule applies to
RunAs Users
Groups of RunAs Users

RunAs Group category the rule applies to
RunAs Groups

It looks like currently one can set RunAs Users and RunAs Groups but not Groups of RunAs Users with ipasudorule.py.

I have no use case for this currently but filing for completeness sake so probably low priority item. Thanks.

**Comment by rjeffman** [comment]
Thank you for the report.

I'm proposing PR #899 to fix this issue.
