### ISSUE TITLE
RFE: ipaclient role should support --subid option

### ISSUE THREAD

**Issue by infra-monkey** [freeipa/ansible-freeipa#919]
Since freeipa 4.9.10 (https://www.freeipa.org/page/Releases/4.9.10) the client installer can enable subid lookup from sssd.
This is done by using the switch `--subid` with ipa-client-install

It would be good to enable the same behavior with the ipaclient role.

**Comment by ikke-t** [comment]
Missing this option leads to non-funcitonal podman. Userspace podman requires /etc/sub[gu]id set, and fails to start anything until they are set. So no userspace containers for this role user until it's added.

**Comment by rjeffman** [comment]
`subid` option has been added to `ipaclient` role with PR #974.
