### ISSUE TITLE
How to run add-topologysegments.yml playbbok? 

### ISSUE THREAD

**Issue by jtudelag** [freeipa/ansible-freeipa#93]
Unfortunately, I could not get some logs, but I have tried to run the add-topologysegments.yml playbook, and I couldn't as Ansible was complaining It could not find some python modules.

Probably I'm doing something wrong, but maybe it is a good idea to re-organize module/module_utils folders in order to make playbook execution easier.

Also add some docs on how to run those playbooks would be good ;).

**Comment by t-woerner** [comment]
It is not possible to load the ansible-freeipa modules and module_utils from the plugins folder directly using anisble-playbook. You can either adapt ansible.cfg:

```
library      = /my/dir/ansible-freeipa/plugins/modules
module_utils = /my/dir/ansible-freeipa/plugins/module_utils
```
or you can link the files:
  `ansible-freeipa/plugins/modules*` to `~/.ansible/plugins/modules/`
  `ansible-freeipa/plugins/module_utils/*` to `~/.ansible/plugins/module_utils/`

There is also a way to use the ansible collection from galaxy, but you need to adapt the names then of the modules to `freeipa.ansible_freeipa.ipatopologysegment`.

**Comment by jtudelag** [comment]
@t-woerner understood then!!!

This PR might address the issue, forcing the right paths in the ansible.cfg. Also tunning it make it faster ;)

https://github.com/freeipa/ansible-freeipa/pull/94

**Comment by jtudelag** [comment]
closing.
