### ISSUE TITLE
Client re-installation fails with /etc/ipa/ca.crt not found error

### ISSUE THREAD

**Issue by aniro** [freeipa/ansible-freeipa#95]
Hi,
First installation on c lean host works fine. However, if I uninstall ipa client either by running 
`ipa-client-install --uninstall -U` or by using `role: ipaclient state=absent`
and try to re-install it using the same role it fails:
```
TASK [ipaclient : Install - IPA API calls for remaining enrollment parts] ****************************************************************************************************************************************************
fatal: [sdtn-vm-001.sedh.group]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 10.202.2.61 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1563222328.73431-49531510135080/AnsiballZ_ipaclient_api.py\", line 114, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1563222328.73431-49531510135080/AnsiballZ_ipaclient_api.py\", line 106, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1563222328.73431-49531510135080/AnsiballZ_ipaclient_api.py\", line 49, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/tmp/ansible_ipaclient_api_payload_rRvg3S/__main__.py\", line 221, in <module>\r\n  File \"/tmp/ansible_ipaclient_api_payload_rRvg3S/__main__.py\", line 101, in main\r\n  File \"/usr/lib/python2.7/site-packages/ipalib/x509.py\", line 446, in load_certificate_list_from_file\r\n    with open(filename, 'rb') as f:\r\nIOError: [Errno 2] No such file or directory: '/etc/ipa/ca.crt'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```
Command line re-installation works fine. 
command line arguments:
```
ipa-client-install --no-ntp --domain 'domain'  --realm 'DOMAIN' -p admin@DOMAIN -w <pass> --mkhomedir --force-join
```
ansible variables:
```
ipaserver_domain: domain
ipaserver_realm: DOMAIN
ipaclient_no_ntp: true
ipaclient_force_join: true
ipaclient_mkhomedir: true
ipaclient_on_master: true
```
Ansible version: 2.8.2
ipa client version: ipa-client-4.6.4-10.el7_6.3.x86_64
os: rhel7.6
ansible-freeipa role version: 0.1.5

**Comment by t-woerner** [comment]
Why are you setting `ipaclient_on_master`? This setting is only used in the server installation process to deploy the client part. It should be not be used otherwise.

**Comment by aniro** [comment]
Probably, I confused the meaning of this property. I thought, it is used to configure ipa servers so that I could login there using IPA users (i.e. by setting up ipa-client on server). 
Apparently it does not seem to be required as IPA server roles already include client part which configures authentication. Is that correct?

From the other side removing this property fixed the issue of client installation on host without any server roles. This seems weird unless the name and description of the property are misleading.

**Comment by t-woerner** [comment]
I have adapted the description of the parameter ipaclient_on_master

> The bool value is only used in the server and replica installation process to install the client part. It should not be set otherwise. ipaclient_on_master defaults to no.

Please close the ticket if this change is sufficient.

**Comment by aniro** [comment]
Hi @t-woerner, thank you for the update of the docs. 
I am still confused, according to my observations:
1. client part is installed and configured on servers even when ipaclient_on_master is not set. 
This is a snippet from ipaserver/tasks/install.yml
```
    - name: Install - Setup client
      include_role:
        name: ipaclient
      vars:
        state: present
        ipaclient_on_master: yes
```
So it implicitly overrides variable to yes

2. If we set this property globally for all hosts related to ipa domain (just to not create one more group for server+replicas for this single property), client re-installation fails on client hosts as was described in the first message.

**Comment by t-woerner** [comment]
@aniro, hopefully this can help to solve your confusion:

The IPA primary master deployment also does a client part deployment. Setting ipaclient_on_master results in a special client deployment needed on the primary master server. The setting is required in this case and may only be used in this case.

The setting ipaclient_on_master may not be used, it is for internal use only.
