### ISSUE TITLE
Realm config parameter is ignored and ipa attempts to join existing AD instead

### ISSUE THREAD

**Issue by IKatsu** [freeipa/ansible-freeipa#964]
Please bear with me as I am rather new to Freeipa.
I am trying to join servers to a small freeipa domain but it is failing because instead of trying to join to the realm in the config file it is detecting the existing MS AD infrastructure and attempting to connect to that instead.
If I do ipa-client-install from the command line it does try the correct realm (but then fails over the certs because I have no prep work ready for a manual join)
I'm assuming this is somehow an issue in the ansible scripts because the manual install attempts the correct realm and connects to it.

**Comment by rjeffman** [comment]
If you are using auto-discovery, there might be some issues with your DNS records. It is hard to guess without more information.

Please make sure you read FreeIPA's [Deployment Recommendation](https://www.freeipa.org/page/Deployment_Recommendations).
