### ISSUE TITLE
Deployment successful - hosts are in domain and working but no host joined is in DNS

### ISSUE THREAD

**Issue by damjankumin** [freeipa/ansible-freeipa#965]
Hello,

using provided ansible, I successfully added many hosts to my local FreeIPA domain. But after joining them, I noticed, that none of the added hosts were added to DNS and naturally cannot be called by hostname. Any hint what may have caused this or how to fix it? I really do not want to go manually as there were quite many.

Thx!

**Comment by rjeffman** [comment]
Did you enabled FreeIPA embedded dns on deployment (`ipaserver_setup_dns=yes`)?

De the client hosts use the server's DNS IP for name resolution (i.e. in /etc/resolv.conf) ?

**Comment by damjankumin** [comment]
oh darn, I have not :/ also, in addition, I thought that that was for the installation of DNS on ipaserver flag - I have also found that installing the replica did not also install DNS on it, so now I have only 1 DNS server out of 2 ipa servers....

**Comment by rjeffman** [comment]
So, what you need to have for automatic DNS entries is to have the embedded DNS deployed along with the server (and/or replicas), and set the nameserver on the client hosts to point to IPA nameservers. It should work, as that's what I use.

Let me know if this does not work for you, so I can investigate.

**Comment by damjankumin** [comment]
okay so that works, I have DNS in ipaserver, clients are using it for DNS and that flag now correctly adds client DNS entries when enrolled...

A quick question - installing DNS server along with ipaserver? How to do that, I presumed that it will be installed along with Ipaserver components... any info on where and what to set so that I have the DNS server also on a replica?

**Comment by rjeffman** [comment]
@damjankumin sorry, but I lost your question.

To install the IPA embedded DNS server (bind) along with an IPA server (primary or replica) with ansible-freeipa use `ipaserver_setup_dns: true` (on ipaserver) or `ipareplica_setup_dns: true` (on ipareplica).

Note that entries will be stored in LDAP and replicated, that means that any global configuration (e.g. global forwarders) will be the same for all servers and should be overridden by server attributes when appropriate.

**Comment by rjeffman** [comment]
One last note: after ansible-freeipao release 1.9.0, instead of changing the client host configuration manually use the variables `ipaclient_configure_dns_resolver`, `ipaclient_dns_servers` and `ipaclient_cleanup_dns_resolver`. Check [ipaclient doocumentation](https://github.com/freeipa/ansible-freeipa/tree/master/roles/ipaclient).
