### ISSUE TITLE
ipareplica setup does not create PTR records for replica IPs

### ISSUE THREAD

**Issue by aniro** [freeipa/ansible-freeipa#97]
Ansible version: 2.8.2
ipa client version: ipa-client-4.6.4-10.el7_6.3.x86_64
os: rhel7.6
ansible-freeipa role version: 0.1.5

Running ipareplica role does not create PTR records of own ip addresses.
Parameters:
```
ipareplica_install_packages: true
ipareplica_setup_firewalld: true
ipareplica_setup_ca: true
ipareplica_setup_dns: true
ipareplica_allow_zone_overlap: true
ipareplica_reverse_zones: 
  - x.x.x.in-addr.arpa
ipareplica_setup_adtrust: true
ipareplica_no_dnssec_validation: true
ipareplica_no_host_dns: true (added later for troubleshooting)
ipareplica_no_forwarders: true
ipaserver_domain: domain
ipaserver_realm: DOMAIN
ipaclient_no_ntp: true
ipaclient_force_join: true
ipaclient_mkhomedir: true
```
There is no signs in the logs about PTR record registration.

Running the same replica installation from command line with corresponding options works fine. PTR record is created automatically:
```
ipa-replica-install \
--principal admin \
--admin-password <pass> \
--setup-dns \
--setup-ca \
--allow-zone-overlap \
--no-ntp \
--reverse-zone=x.x.x.in-addr.arpa \
--setup-adtrust \
--no-dnssec-validation \
--no-forwarders  \
--force-join
```
I can see the following in /var/log/ipareplica-install.log
```
2019-07-16T14:19:27Z DEBUG dnsrecord_add(<DNS name x.x.x.in-addr.arpa.>, <DNS name 13>, a_extra_create_reverse=False, aaaa_extra_create_reverse=False, ptrrecord=(u'hostname.domain.',), force=False, structured=False, all=False, raw=False, version=u'2.230')
```

**Comment by t-woerner** [comment]
I have pushed several changes today, there is also one related to dns setup: https://github.com/freeipa/ansible-freeipa/commit/6378d9b1dc8730e5379aaa29d74a7ec499476616

It might already fix your issue.

**Comment by aniro** [comment]
I can confirm that v0.1.6 fixed the issue.
