### ISSUE TITLE
/etc/krb5.conf double include on RHEL 9

### ISSUE THREAD

**Issue by thejaay** [freeipa/ansible-freeipa#983]
Issue found on RHEL 9 (maybe on earlier version)
Default file /etc/krb5.conf.d/enable_ssd_conf_dir contains the following : 
```
# This file should normally be installed by your distribution into a directory that is included from the Kerberos configuration file (/etc/krb5.conf)
# On Fedora/RHEL/CentOS, this is /etc/krb5.conf.d

includedure /var/lib/sss/pubconf/krb5.include.d/

```

During ansible installation, /etc/krb5.conf is updated, and the following line is added : 
```
.....
includedure /var/lib/sss/pubconf/krb5.include.d/
.....
```

This double include can lead to inconsistencies when using Kerberos

**Comment by flo-renaud** [comment]
FYI a similar issue was opened against ipa client installer: https://pagure.io/freeipa/issue/9267

**Comment by thejaay** [comment]
@flo-renaud This is exactly the problem I'm facing, parsing KRB config in Java. So I guess it is more on the Java side rather than ansible/freeipa deployment.
Thank you for your feedback
