### ISSUE TITLE
Memory leak - ns-slapd

### ISSUE THREAD

**Issue by RIBO46** [freeipa/ansible-freeipa#985]
ns-slapd processes are leaking memory. I saw a lot of similar topics, but not a single solution, has anyone dealt with such a problem?

**Comment by rjeffman** [comment]
This is an issue in `FreeIPA`, not in `ansible-freipa`.

Please report the issue to the FreeIPA project using this link [https://pagure.io/freeipa/issues](https://pagure.io/freeipa/issues)
