### ISSUE TITLE
[RFE]ipa_host module to allow otp generation

### ISSUE THREAD

**Issue by jtudelag** [freeipa/ansible-freeipa#99]
Currently, the [ipa_host](https://docs.ansible.com/ansible/latest/modules/ipa_host_module.html) module does not expose the "Generate OTP" option, that it is available through the web interface. (I guess through the API as well)

It will very useful to expose it in the module.

A sample use case is Linux host provisioning. Creating first the host in IPA, getting the OTP and then provisiong the host and enrolling in IPA without sharing wider credentials.

**Comment by t-woerner** [comment]
The ipa_host module is provided by Ansible upstream. ansible-freeipa is also providing a management module for users: https://github.com/freeipa/ansible-freeipa/blob/master/README-user.md
I think this might be a really good addition to this module.

**Comment by jtudelag** [comment]
You are completely right @t-woerner, actually was checking the code and it seems it is already there.
https://github.com/ansible/ansible/blob/f92b95b8cbd13c6bb49a7594b4ba58f2ca16e602/lib/ansible/modules/identity/ipa/ipa_host.py#L243

I might have been confused by the term "random_password" in the module documentation...
https://docs.ansible.com/ansible/latest/modules/ipa_host_module.html
