### ISSUE TITLE
Running ipaclient on masters and replicas (ipaclient_on_master?)

### ISSUE THREAD

**Issue by hakong** [freeipa/ansible-freeipa#990]
(This is a question, not a bug).

When deploying ipaclient on multiple hosts with Foreman I assigned the ipaclient ansible role to all top-level hostgroups, thus all hosts inherit the ipaclient role.

This casued some issues when running the client role on servers (deleting keytab) and took down the entire IPA environment.

I just noticed the `ipaclient_on_master` parameter that seems to skip certain things when configuring the ipa client. Is this what this parameter is intended for? Would it be safe to include the client role on all IPA servers if this parameter is set to `true`? Even if parameters like `ipaclient_force_join` and `ipaclient_allow_repair` are set to `true`?

**Comment by t-woerner** [comment]
With `ipaclient_allow_repair` the ipaclient role will try to repair a client deployment. `ipaclient_force_join` will force a new client join.

`ipaclient_on_master` is only for internal use and not supported to be used otherwise.

The ipaclient role is only supported for clients, not for servers.

**Comment by hakong** [comment]
Thanks for the clarification. That complicates things a bit. It would be nice if the client role would detect it's being run on a master/replica and don't touch anything.

For organizations that deploy the IPA client environment-wide with something like Foreman/Satellite, we apply the role on a very high level for hostgroups meaning we don't have to apply it for each host or sub-hostgroup. Problem is that some hostgroups contain IPA servers and there is no way to exclude roles being run on a per-host basis if it inherits it from above.

Would a master/replica-detection feature in the client role be of any interest? Something that would skip installing and configuring the client if it detected the host being a IPA server. And if not an auto-detect feature, what about a variable?

I realize this is not an issue with the roles but more how you use them. Still, for practical purposes this would be nice.

**Comment by hakong** [comment]
I just ran the client role on a server with `ipaclient_on_master = True` and it behaved more or less the way I expected it to. Didn't change anything. But if this isn't recommended or supported I'll have to find another way.

**Comment by abbra** [comment]
@hakong `--on-master` switch is used by the IPA server (primary or replica) installer to cause a partial configuration of the client. This partial configuration assumes the rest is configured by the server installer. Without that the client is not really a client yet -- it has no keys downloaded, it is configured to only query itself rather than going to any other server, etc. Since the server is not yet configured, the client is not a client yet.

That's why it is 'internal' switch. It is not documented in the client's installer man page, it is marked  in the code as deprecated to hide it from the command line help output:
```
    on_master = knob(
        None,
        deprecated=True,
    )
```

**Comment by hakong** [comment]
Thanks for the clarification. I have replaced the ipaclient role with a custom role that only imports it on clients, so I can keep it it assigned to top-level hostgroups but still prevent it from running on ipa servers.

**Comment by hakong** [comment]
I'll ask in TheForeman forums if there is a better way of doing this in Foreman/Satellite.
