### ISSUE TITLE
issue warning when trying to configure an ipareplica on a non-ipaclient

### ISSUE THREAD

**Issue by RobVerduijn** [freeipa/ansible-freeipa#993]
Hello,

When you try to configure a host as a ipa-replica when it is not configured as an ipa-client of the domain, the ipareplica role gives a fuzzy warning about the realm not being set in the env.

It should complain about the host not being an ipa-client of the domain.
Or it should first configure the host as an ipa-client before proceeding.

Rob

**Comment by rjeffman** [comment]
What is the actual message that you are observing? Is your domain discoverable through DNS records on the replica host?

**Comment by t-woerner** [comment]
The replica role is at first doing a client deployment and afterwards it is promoting the client to a replica (same process as the command line client).
Please add the error lines from the log files.

**Comment by RobVerduijn** [comment]
sry for the delay,

I must have made some silly typo somewhere cause today the installation worked like a charm

Rob
